/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.AddChannelConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.AddChannelConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.AddChannelConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.AddChannelConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.AddChannelConfigMgr.WINDOW  iscom.jsjn.jnf.config.AddChannelConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.AddChannelConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.AddChannelConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.AddChannelConfigMgr", function(){
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('channelType.AddChannelConfigMgr'), {
		store : tradeTypeStore.getStore()
	});	
});

/**
 * 新增
 */
com.jsjn.jnf.config.AddChannelConfigMgr.save = function(){
	
	var channelId =  Ext.getCmp('channelId.AddChannelConfigMgr').getValue();
	var channelName = Ext.getCmp('channelName.AddChannelConfigMgr').getValue();
	var fee = Ext.getCmp('fee.AddChannelConfigMgr').getValue();
	var channelType = Ext.getCmp('channelType.AddChannelConfigMgr').getValue();
	
	if(valueIsEmpty(channelId)){
		Ext.Msg.alert('系统提示', '渠道编号不能为空!');
		return false;
	}
	if(valueIsEmpty(channelName)){
		Ext.Msg.alert('系统提示', '渠道名称不能为空!');
		return false;
	}
	if(valueIsEmpty(fee)){
		Ext.Msg.alert('系统提示', '第三方渠道收费（笔）不能为空!');
		return false;
	}
	
	var url = 'jnf/channelService.do?method=addChannel';
	var param = {'channelId':channelId,
				'channelName':channelName,			
				'fee':fee,			
				'channelType':channelType		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.ChannelConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "新增成功！", function() {
				com.jsjn.jnf.config.AddChannelConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "新增失败！"+resMsg, function(){});
		}
	
	});
	
};

/**
 * 关闭
 */
com.jsjn.jnf.config.AddChannelConfigMgr.close = function(){
	
	com.jsjn.jnf.config.AddChannelConfigMgr.WINDOW.hide();
};