/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.AddMenuConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.AddMenuConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.AddMenuConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.AddMenuConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.AddMenuConfigMgr.WINDOW  iscom.jsjn.jnf.config.AddMenuConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.AddMenuConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.AddMenuConfigMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.config.AddMenuConfigMgr", function(){
	
});

/**
 * 新增
 */
com.jsjn.jnf.config.AddMenuConfigMgr.save = function(){
	
	var menuCde =  Ext.getCmp('menuCde.AddMenuConfigMgr').getValue();
	var menuKey = Ext.getCmp('menuKey.AddMenuConfigMgr').getValue();
	var menuValue = Ext.getCmp('menuValue.AddMenuConfigMgr').getValue();
	var menuSort = Ext.getCmp('menuSort.AddMenuConfigMgr').getValue();
	
	
	if(valueIsEmpty(menuCde)){
		Ext.Msg.alert('系统提示', '选项代码不能为空!');
		return false;
	}
	if(valueIsEmpty(menuKey)){
		Ext.Msg.alert('系统提示', '选项序号不能为空!');
		return false;
	}
	if(valueIsEmpty(menuValue)){
		Ext.Msg.alert('系统提示', '字典标签不能为空!');
		return false;
	}
	if(valueIsEmpty(menuSort)){
		Ext.Msg.alert('系统提示', '字典类型不能为空!');
		return false;
	}
	
	var url = 'jnf/menuConfigService.do?method=addMenu';
	var param = {'menuCde':menuCde,
				'menuKey':menuKey,			
				'menuValue':menuValue,			
				'menuSort':menuSort		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.MenuConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "新增成功！", function() {
				com.jsjn.jnf.config.AddMenuConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "新增失败！"+resMsg, function(){});
		}
	
	});
	
};

/**
 * 关闭
 */
com.jsjn.jnf.config.AddMenuConfigMgr.close = function(){
	
	com.jsjn.jnf.config.AddMenuConfigMgr.WINDOW.hide();
};
