/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.ChannelConfigListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.ChannelConfigListMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.ChannelConfigListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.ChannelConfigListMgr.PANEL is com.jsjn.jnf.config.ChannelConfigListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.ChannelConfigListMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.config.ChannelConfigListMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.ChannelConfigListMgr",function() {
		
});

com.jsjn.jnf.config.ChannelConfigListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var dataIndex = Ext.getCmp("grid.ChannelConfigListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'fee') {
		return formatMoney(value);
	}
	if (dataIndex == 'channelType') {
		return storeFind(tradeTypeStore, value);
	}
	if (dataIndex == 'operator') {
		var operater = "";
		operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.config.ChannelConfigListMgr.update();\" style=\"vertical-align:bottom; text-decoration:none\">【修改】</a>";
		operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.config.ChannelConfigListMgr.del();\" style=\"vertical-align:bottom; text-decoration:none\">【删除】</a>";
		return operater;
	}
	
	return value;
};

/**
 * 点击查询按钮
 */
com.jsjn.jnf.config.ChannelConfigListMgr.btnQuery = function(){
	
	Ext.getCmp('grid.ChannelConfigListMgr').getStore().load();
	
};

/**
 * 新增计费种类信息
 */
com.jsjn.jnf.config.ChannelConfigListMgr.btnAdd = function(){
	
	var win = appframe.getInstance("com.jsjn.jnf.config.AddChannelConfigMgr");

	win.show();
	
	//清空新增 信息
	Ext.getCmp('form.AddChannelConfigMgr').getForm().reset();
};

/**
 * 修改计费种类信息
 */
com.jsjn.jnf.config.ChannelConfigListMgr.btnUpdate = function(){
	
	var record = Ext.getCmp('grid.ChannelConfigListMgr').getSelectionModel().getSelected();
	if(record=="undefined"||record==null){
		 Ext.MessageBox.alert('提示', '请选中你要操作的数据');
		return;
	}
	var win = appframe.getInstance("com.jsjn.jnf.config.UpdateChannelConfigMggr");
	
	win.show();
	
	com.jsjn.jnf.config.UpdateChannelConfigMggr.panelInit(record);
	
};

/**
 * 删除该笔计费种类信息
 */
com.jsjn.jnf.config.ChannelConfigListMgr.btnDelete = function(){
	var record = Ext.getCmp('grid.ChannelConfigListMgr').getSelectionModel().getSelected();
	if(record=="undefined"||record==null){
		 Ext.MessageBox.alert('提示', '请选中你要操作的数据');
		return;
	}
	Ext.MessageBox.confirm("提示", '您确定要删除该渠道配置吗？', function(btn) {
        if (btn == 'yes') {
        	var channelId = record.data.channelId;
        	var url = 'jnf/channelService.do?method=delChannel';
        	var param = {
        				'channelId':channelId
        				};
        	ajaxLoad(url, param, '', '', '', function(response) {
        		var success = Ext.decode(response.responseText).success;
        		var resMsg = Ext.decode(response.responseText).resMsg;
//        		var temp = Ext.decode(response.responseText).root;
        		if(success){
        			Ext.getCmp('grid.ChannelConfigListMgr')
        			.getStore().reload();
        			Ext.Msg.alert("系统提示", "删除成功！", function() {
        			});
        		}else{
        			Ext.Msg.alert("系统提示", "删除失败！"+resMsg, function(){});
        		}
        	
        	});
        }
    });
	
};