/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.FeeConfigListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.FeeConfigListMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.FeeConfigListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.FeeConfigListMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.FeeConfigListMgr.WINDOW  iscom.jsjn.jnf.config.FeeConfigListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.FeeConfigListMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.FeeConfigListMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.FeeConfigListMgr",function() {
//		girdStoreAddExceptionEvent('grid.FeeConfigListMgr',
//		"com.jsjn.jnf.config.FeeConfigListMgr");
		
});


com.jsjn.jnf.config.FeeConfigListMgr.panelInit = function(record){
	
	var mid = record.json.mid;			//商户号
	
	Ext.getCmp('mid.FeeConfigListMgr').setValue(mid);
	
	com.jsjn.jnf.config.FeeConfigListMgr.addParams();
	
};

com.jsjn.jnf.config.FeeConfigListMgr.addParams = function() {
	var mid = Ext.getCmp('mid.FeeConfigListMgr').getValue();	//商户名称
	
	var params = {
			mid : mid
	};
	
	var gStore = Ext.getCmp('grid.FeeConfigListMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.config.FeeConfigListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	com.jsjn.jnf.config.FeeConfigListMgr.id = record.data.id;
	
	var dataIndex = Ext.getCmp("grid.FeeConfigListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'operator') {
		var operater = "";
		operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.config.FeeConfigListMgr.update();\" style=\"vertical-align:bottom; text-decoration:none\">【修改】</a>";
		operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.config.FeeConfigListMgr.del();\" style=\"vertical-align:bottom; text-decoration:none\">【删除】</a>";
		return operater;
	}
	if (dataIndex == 'startTime') {
		return value.substring(0,10);
	}
	if (dataIndex == 'endTime') {
		return value.substring(0,10);
	}
	if (dataIndex == 'feeType') {
		return storeFind(feeTypeStore, value);
	}
	if (dataIndex == 'fee') {
		return formatMoney(value);
	}
	if (dataIndex == 'mname') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	
	return value;
};

/**
 * 新增计费种类信息
 */
com.jsjn.jnf.config.FeeConfigListMgr.addBtn = function(){
	
	var win = appframe.getInstance("com.jsjn.jnf.config.AddConfigMgr");

	win.show();
	
	//清空新增 信息
	Ext.getCmp('form.AddConfigMgr').getForm().reset();
};

/**
 * 修改计费种类信息
 */
com.jsjn.jnf.config.FeeConfigListMgr.update = function(){
	
	var record = Ext.getCmp('grid.FeeConfigListMgr').getSelectionModel().getSelected();
	
	var win = appframe.getInstance("com.jsjn.jnf.config.UpdateConfigMgr");
	
	win.show();
	
	com.jsjn.jnf.config.UpdateConfigMgr.panelInit(record);
	
};

/**
 * 删除该笔计费种类信息
 */
com.jsjn.jnf.config.FeeConfigListMgr.del = function(){
	
	Ext.MessageBox.confirm("提示", '您确定要删除该笔计费种类吗？', function(btn) {
        if (btn == 'yes') {
        	var id = com.jsjn.jnf.config.FeeConfigListMgr.id;
        	var url = 'jnf/feeConfigService.do?method=delFeeConfig';
        	var param = {
        				'id':id
        				};
        	ajaxLoad(url, param, '', '', '', function(response) {
        		var success = Ext.decode(response.responseText).success;
        		var resMsg = Ext.decode(response.responseText).resMsg;
//        		var temp = Ext.decode(response.responseText).root;
        		if(success){
        			Ext.getCmp('grid.FeeConfigListMgr')
        			.getStore().reload();
        			Ext.Msg.alert("系统提示", "删除成功！", function() {
        			});
        		}else{
        			Ext.Msg.alert("系统提示", "删除失败！"+resMsg, function(){});
        		}
        	
        	});
        }
    });
	
};
