/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.UpdateChannelBankConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.UpdateChannelBankConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.UpdateChannelBankConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.UpdateChannelBankConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.UpdateChannelBankConfigMgr.WINDOW  iscom.jsjn.jnf.config.UpdateChannelBankConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.UpdateChannelBankConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.UpdateChannelBankConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.UpdateChannelBankConfigMgr", function() {
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('channelId.UpdateChannelBankConfigMgr'), {
		store : withholdChannelStore.getStore()
	});	
	
	reSetComboValue(['channelId.UpdateChannelBankConfigMgr']);
});

//回显理财详细信息
com.jsjn.jnf.config.UpdateChannelBankConfigMgr.panelInit=function(record){
	
	var channelId = record.data.channelId;			
	var jnBankCode = record.data.jnBankCode;		
	var maxAmount = record.data.maxAmount;
	var bankName = record.data.bankName;
	var channelBankCode = record.data.channelBankCode;
	var maxAmountDay = record.data.maxAmountDay;

	Ext.getCmp('channelId.UpdateChannelBankConfigMgr').setValue(channelId);
	Ext.getCmp('jnBankCode.UpdateChannelBankConfigMgr').setValue(jnBankCode);
	Ext.getCmp('maxAmount.UpdateChannelBankConfigMgr').setValue(maxAmount);
	Ext.getCmp('bankName.UpdateChannelBankConfigMgr').setValue(bankName);
	Ext.getCmp('channelBankCode.UpdateChannelBankConfigMgr').setValue(channelBankCode);
	Ext.getCmp('maxAmountDay.UpdateChannelBankConfigMgr').setValue(maxAmountDay);
	
};

//关闭
com.jsjn.jnf.config.UpdateChannelBankConfigMgr.close = function() {
	
	com.jsjn.jnf.config.UpdateChannelBankConfigMgr.WINDOW.hide();
	
};

//修改
com.jsjn.jnf.config.UpdateChannelBankConfigMgr.save = function() {
	
	var channelId =  Ext.getCmp('channelId.UpdateChannelBankConfigMgr').getValue();
	var jnBankCode = Ext.getCmp('jnBankCode.UpdateChannelBankConfigMgr').getValue();
	var maxAmount = Ext.getCmp('maxAmount.UpdateChannelBankConfigMgr').getValue();
	var bankName = Ext.getCmp('bankName.UpdateChannelBankConfigMgr').getValue();
	var channelBankCode = Ext.getCmp('channelBankCode.UpdateChannelBankConfigMgr').getValue();
	var maxAmountDay = Ext.getCmp('maxAmountDay.UpdateChannelBankConfigMgr').getValue();
	
	if(valueIsEmpty(bankName)){
		Ext.Msg.alert('系统提示', '银行名称不能为空!');
		return false;
	}
	if(valueIsEmpty(channelBankCode)){
		Ext.Msg.alert('系统提示', '渠道银行CODE不能为空!');
		return false;
	}
	
	var url = 'jnf/channelBankService.do?method=updateBankInfo';
	var param = {'channelId':channelId,
				'jnBankCode':jnBankCode,			
				'maxAmount':maxAmount,			
				'bankName':bankName,	
				'channelBankCode':channelBankCode,	
				'maxAmountDay':maxAmountDay	
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.ChannelBankConfigMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "修改成功！", function() {
				com.jsjn.jnf.config.UpdateChannelBankConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "修改失败！"+resMsg, function(){});
		}
	
	});
};