/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.UpdateChannelConfigMggr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.UpdateChannelConfigMggr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.UpdateChannelConfigMggr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.UpdateChannelConfigMggr.main method is the beginning of all.
 * com.jsjn.jnf.config.UpdateChannelConfigMggr.WINDOW  iscom.jsjn.jnf.config.UpdateChannelConfigMggr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.UpdateChannelConfigMggr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.UpdateChannelConfigMggr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.UpdateChannelConfigMggr", function() {
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('channelType.UpdateChannelConfigMggr'), {
		store : tradeTypeStore.getStore()
	});	
	
	reSetComboValue(['channelType.UpdateChannelConfigMggr']);
});

//回显理财详细信息
com.jsjn.jnf.config.UpdateChannelConfigMggr.panelInit=function(record){
	
	com.jsjn.jnf.config.UpdateChannelConfigMggr.channelId = record.data.channelId;			//序号
	var channelId = record.data.channelId;			
	var channelName = record.data.channelName;		
	var fee = record.data.fee;
	var channelType = record.data.channelType;

	Ext.getCmp('channelId.UpdateChannelConfigMggr').setValue(channelId);
	Ext.getCmp('channelName.UpdateChannelConfigMggr').setValue(channelName);
	Ext.getCmp('fee.UpdateChannelConfigMggr').setValue(fee);
	Ext.getCmp('channelType.UpdateChannelConfigMggr').setValue(channelType);
	
};

//关闭
com.jsjn.jnf.config.UpdateChannelConfigMggr.close = function() {
	
	com.jsjn.jnf.config.UpdateChannelConfigMggr.WINDOW.hide();
	
};

//修改
com.jsjn.jnf.config.UpdateChannelConfigMggr.update = function() {
	
	var channelId =  Ext.getCmp('channelId.UpdateChannelConfigMggr').getValue();
	var channelName = Ext.getCmp('channelName.UpdateChannelConfigMggr').getValue();
	var fee = Ext.getCmp('fee.UpdateChannelConfigMggr').getValue();
	var channelType = Ext.getCmp('channelType.UpdateChannelConfigMggr').getValue();
	
	if(valueIsEmpty(channelId)){
		Ext.Msg.alert('系统提示', '渠道编号不能为空!');
		return false;
	}
	if(valueIsEmpty(channelName)){
		Ext.Msg.alert('系统提示', '渠道名称不能为空!');
		return false;
	}
	if(valueIsEmpty(fee)){
		Ext.Msg.alert('系统提示', '第三方渠道收费（笔）不能为空!');
		return false;
	}
	
	var url = 'jnf/channelService.do?method=updateChannel';
	var param = {'channelId':channelId,
				'channelName':channelName,			
				'fee':fee,			
				'channelType':channelType		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.ChannelConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "修改成功！", function() {
				com.jsjn.jnf.config.UpdateChannelConfigMggr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "修改失败！"+resMsg, function(){});
		}
	
	});
};