/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.AccessConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.AccessConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.AccessConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.AccessConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.member.AccessConfigMgr.WINDOW  iscom.jsjn.jnf.member.AccessConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.AccessConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.member.AccessConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.member.AccessConfigMgr",function() {
		
});

com.jsjn.jnf.member.AccessConfigMgr.panelInit = function(record){
	//页面初始加载时，将输入框置为可编辑 ，隐藏的设置为不可以见
	Ext.getCmp('whiteList.AccessConfigMgr').enable();
	Ext.getCmp('rsaPubKey.AccessConfigMgr').enable();
	Ext.getCmp('hiden.AccessConfigMgr').hide();
	
	var mid = record.data.mid;		//商户编号
	
	//发ajax请求，查询商户配置信息
	if(valueIsEmpty(mid)){
		Ext.Msg.alert('系统提示', '商户号不能为空!');
		return false;
	}
	var url = '/jnf/bussinessConfigService.do?method=queryBussinessConfigByMid';
	var param = {
				'mid':mid,
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
		var rsp = Ext.decode(response.responseText).root;
		var data = Ext.util.JSON.decode(rsp);
		
		//返回成功，且已经有记录 （修改）
		if(success && data != ''){
			Ext.getCmp('mid.AccessConfigMgr').setValue(data.mid);
			Ext.getCmp('appkey.AccessConfigMgr').setValue(data.appkey);
			Ext.getCmp('whiteList.AccessConfigMgr').setValue(data.whiteList);
			Ext.getCmp('rsaPubKey.AccessConfigMgr').setValue(data.rsaPubKey);
			
			//判断数据是否被篡改
			com.jsjn.jnf.member.AccessConfigMgr.valid = data.valid;
			if(!com.jsjn.jnf.member.AccessConfigMgr.valid){
				Ext.getCmp('whiteList.AccessConfigMgr').disable();
				Ext.getCmp('rsaPubKey.AccessConfigMgr').disable();
				Ext.getCmp('hiden.AccessConfigMgr').show();
			}
			
		}else if(success && data == ''){
			//返回成功 但是没有记录 （新增）
			Ext.getCmp('mid.AccessConfigMgr').setValue(mid);
			Ext.getCmp('appkey.AccessConfigMgr').setValue('');
			Ext.getCmp('whiteList.AccessConfigMgr').setValue('');
			Ext.getCmp('rsaPubKey.AccessConfigMgr').setValue('');
			
		}else{
			Ext.Msg.alert("系统提示", "查询失败！"+resMsg, function(){});
		}
	
	});
};

//保存功能
com.jsjn.jnf.member.AccessConfigMgr.save = function(){
	//如果数据被篡改，不允许提交
	if(!com.jsjn.jnf.member.AccessConfigMgr.valid){
		Ext.Msg.alert("系统提示", "数据被篡改，不允许提交！", function(){});
		return;
	}
	
	
	var mid =  Ext.getCmp('mid.AccessConfigMgr').getValue();
	var appkey = Ext.getCmp('appkey.AccessConfigMgr').getValue();
	var whiteList = Ext.getCmp('whiteList.AccessConfigMgr').getValue();	//白名单
	var rsaPubKey = Ext.getCmp('rsaPubKey.AccessConfigMgr').getValue();	//商户公钥
	
	//发ajax请求，查询商户配置信息
	if(valueIsEmpty(whiteList)){
		Ext.Msg.alert('系统提示', '白名单不能为空!');
		return false;
	}
	if(valueIsEmpty(rsaPubKey)){
		Ext.Msg.alert('系统提示', '商户公钥不能为空!');
		return false;
	}
	var url = '/jnf/bussinessConfigService.do?method=saveBussinessConfig';
	var param = {
				'mid':mid,
				'appkey':appkey,
				'whiteList':whiteList,
				'rsaPubKey':rsaPubKey
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
		var rsp = Ext.decode(response.responseText).root;
		var data = Ext.util.JSON.decode(rsp);
		
		//保存
		if(success){
			Ext.Msg.alert("系统提示", "保存成功！", function(){});
			com.jsjn.jnf.member.AccessConfigMgr.close();
		}else{
			Ext.Msg.alert("系统提示", "保存失败！"+resMsg, function(){});
		}
	
	});
};

//关闭功能
com.jsjn.jnf.member.AccessConfigMgr.close = function(){
	com.jsjn.jnf.member.AccessConfigMgr.WINDOW.hide();
};
