/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.CreateBusnessMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.CreateBusnessMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.CreateBusnessMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.CreateBusnessMgr.PANEL is com.jsjn.jnf.member.CreateBusnessMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.CreateBusnessMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.member.CreateBusnessMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.member.CreateBusnessMgr",function() {
	   com.jsjn.jnf.member.CreateBusnessMgr.initAjax();
});

com.jsjn.jnf.member.CreateBusnessMgr.initAjax = function(){
	Ext.Ajax.request({
	    method : "POST",
	    url : appConfig.baseUrl + '/jnf/qryNewBusness.do?method=qryRoleAll',
	    success : function(response) {
	        var result = Ext.decode(response.responseText);
	        if (result.success) {
	        	var data = result.perList;
	        	var myCheckboxItems = [];    
	        	for(var i=0;i<data.length;i++){
	        		  var boxLabel = data[i].desc;
		                var name = data[i].rid;
		                myCheckboxItems.push({    
		                            boxLabel : boxLabel,    
		                            name : name    
		                        });    
	        	}
	        	var myCheckboxGroup = new Ext.form.CheckboxGroup({    
	                xtype : 'checkboxgroup',    
	                itemCls : 'x-check-group-alt',
	                id:'group.checkbox',
	                name :'insTypeCb', 
	                msgTarget:"side",
	                columns:5,
	                anchor:'60%',
	                layout : 'form',
	               msgTarget:"side",
	                items : myCheckboxItems    
	            });    
	        	var panel = Ext.getCmp('pan.checkbox');
	        	panel.add(myCheckboxGroup);
	        	panel.doLayout();
	        }
	    }
	});
};

com.jsjn.jnf.member.CreateBusnessMgr.createExit = function(button, event){
	window.location.replace(appConfig.baseUrl+"/com.jsjn.jnf.member.QryNewBussnessMgr.view");
};

com.jsjn.jnf.member.CreateBusnessMgr.createSave = function(button, event){
	com.jsjn.jnf.member.CreateBusnessMgr.ajaxCreateBusness();
};

com.jsjn.jnf.member.CreateBusnessMgr.ajaxCreateBusness = function(){
	var mid = Ext.getCmp('mid.amendBusness').getValue();
	var mName = Ext.getCmp('mName.amendBusness').getValue();
	var busLcnsNo = Ext.getCmp('busLcnsNo.amendBusness').getValue();
	var phoneNo = Ext.getCmp('phoneNo.amendBusness').getValue();
	var addr = Ext.getCmp('addr.amendBusness').getValue();
	var status = "";
	if(Ext.getCmp('status.noraml').checked){
		status = 1;
	}else{
		status = 2;
	}
	var appKey = Ext.getCmp('appKey.amendBusness').getValue();
	var whiteList = Ext.getCmp('whiteList.amendBusness').getValue();
	var rsaPubKey = Ext.getCmp('rsaPubKey.amendBusness').getValue();
	var myCheckboxGroup = Ext.getCmp('group.checkbox').items;
	   var cbitems = myCheckboxGroup.items;    
	   var roles = [];
    for (var i = 0; i < cbitems.length; i++) {    
 	   if(cbitems[i].checked){
 		   roles.push(cbitems[i].name);
 	   }
    } 
	Ext.Ajax.request({
	    params : {
	        mid :mid,
	        mName:mName,
	        busLcnsNo:busLcnsNo,
	        phoneNo:phoneNo,
	        addr:addr,
	        status:status,
	        appkey:appKey,
	        whiteList:whiteList,
	        rsaPubKey:rsaPubKey,
	        roles:roles.join(",").toString()
	    },
	    method : "POST",
	    url : appConfig.baseUrl + '/jnf/qryNewBusness.do?method=createBusness',
	    success : function(response) {
	        var result = Ext.decode(response.responseText);
	        if (result.success) {
	        	 Ext.MessageBox.alert('提示', result.infoMsg);
	        	 window.location.replace(appConfig.baseUrl+"/com.jsjn.jnf.member.QryNewBussnessMgr.view");
	        } else {
	            Ext.MessageBox.alert('提示', result.infoMsg);
	        }
	    }
	});
};

