/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.QryMemberListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.QryMemberListMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.QryMemberListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.QryMemberListMgr.PANEL is com.jsjn.jnf.member.QryMemberListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.QryMemberListMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.member.QryMemberListMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.member.QryMemberListMgr",function() {
		girdStoreAddExceptionEvent('grid.QryMemberListMgr',
		"com.jsjn.jnf.member.QryMemberListMgr");
		
		//渲染下拉框
		Ext.apply(Ext.getCmp('idType.QryMemberListMgr'), {
			store : idTypeStore.getStore()
		});	
		
		Ext.apply(Ext.getCmp('custType.QryMemberListMgr'), {
			store : custTypeStore.getStore()
		});	
		
		Ext.getCmp('grid.QryMemberListMgr').getView().getRowClass=function(record,rowIndex,rowParams,store){
		    var valid = record.json.valid;
			if(valid == false){
				return 'x-grid-record-red';
			};
		};
		
});

com.jsjn.jnf.member.QryMemberListMgr.addParams = function() {
	var custId = Ext.getCmp('custId.QryMemberListMgr').getValue();	//客户号
	var mId = Ext.getCmp('mId.QryMemberListMgr').getValue();	//商户编号
	var modifiedMin = Ext.getCmp('modifiedMin.QryMemberListMgr').getRawValue(); //认证时间（起）
	var custName = Ext.getCmp('custName.QryMemberListMgr').getValue(); //客户名称
	var idType = Ext.getCmp('idType.QryMemberListMgr').getValue(); //证件类型
	var modifiedMax = Ext.getCmp('modifiedMax.QryMemberListMgr').getRawValue(); //认证时间（止）
	var custType = Ext.getCmp('custType.QryMemberListMgr').getValue(); //客户类型
	var idNo = Ext.getCmp('idNo.QryMemberListMgr').getValue(); //证件号码

	if( modifiedMin > modifiedMax){
		Ext.Msg.alert('系统提示', '认证时间（起）不能大于认证时间（止）');
		return false;
	}
	
	var params = {
			custId : custId,
			mId : mId,
			beginTime : modifiedMin,
			custName : custName,
			idType : idType,
			endTime : modifiedMax,
			custType : custType,
			idNo : idNo
	};
	
	var gStore = Ext.getCmp('grid.QryMemberListMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.member.QryMemberListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var valid = record.json.valid;//数据是否被篡改
	
	var dataIndex = Ext.getCmp("grid.QryMemberListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'operator') {
		var operater = "";
		if(valid == false){
			operater += "警告：数据被篡改";
		}else{
			operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.member.QryMemberListMgr.detail();\" style=\"vertical-align:bottom; text-decoration:none\">【详情】</a>";
		}
		return operater;
	}
	if (dataIndex == 'custType') {
		return storeFind(custTypeStore, value);
	}
	if (dataIndex == 'idType') {
		return storeFind(idTypeStore, value);
	}
	if (dataIndex == 'state') {
		return storeFind(memberStateStore, value);
	}
	if (dataIndex == 'modified') {
		return formatDateToPattern("YYYY-MM-DD",new Date(new Number(value)));
	}
	if (dataIndex == 'failReason') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	
	return value;
};


/**
 * 点击查询按钮
 */
com.jsjn.jnf.member.QryMemberListMgr.btnQuery = function(){
	
	Ext.getCmp('grid.QryMemberListMgr').getStore().load();
};

/**
 * 点击重置按钮
 */
com.jsjn.jnf.member.QryMemberListMgr.btnReset = function(){
	Ext.getCmp('form.QryMemberListMgr').getForm().reset();
};

/**
 * 详情按钮
 */
com.jsjn.jnf.member.QryMemberListMgr.detail = function(){
	var record = Ext.getCmp('grid.QryMemberListMgr').getSelectionModel().getSelected();
	
	var win = appframe.getInstance("com.jsjn.jnf.member.MemberInfoDetailMgr");
	
	win.show();
	
	com.jsjn.jnf.member.MemberInfoDetailMgr.panelInit(record);
};