/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.UpdateBussinessMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.UpdateBussinessMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.UpdateBussinessMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.UpdateBussinessMgr.main method is the beginning of all.
 * com.jsjn.jnf.member.UpdateBussinessMgr.WINDOW  iscom.jsjn.jnf.member.UpdateBussinessMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.UpdateBussinessMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.member.UpdateBussinessMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.member.UpdateBussinessMgr", function() {
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('status.UpdateBussinessMgr'), {
		store : signStatusStore.getStore()
	});	
	
	reSetComboValue(['status.UpdateBussinessMgr']);
});

//回显理财详细信息
com.jsjn.jnf.member.UpdateBussinessMgr.panelInit=function(record){
	var mid = record.data.mid;		//商户编号
	var mName = record.data.mName;	//商户名称
	var busLcnsNo = record.data.busLcnsNo;	//营业执照
	var phoneNo = record.data.phoneNo;//联系电话
	var addr = record.data.addr;//联系地址
	var status = record.data.status;	//状态

	Ext.getCmp('mid.UpdateBussinessMgr').setValue(mid);
	Ext.getCmp('mName.UpdateBussinessMgr').setValue(mName);
	Ext.getCmp('busLcnsNo.UpdateBussinessMgr').setValue(busLcnsNo);
	Ext.getCmp('phoneNo.UpdateBussinessMgr').setValue(phoneNo);
	Ext.getCmp('addr.UpdateBussinessMgr').setValue(addr);
	Ext.getCmp('status.UpdateBussinessMgr').setValue(status);
	
};

//关闭
com.jsjn.jnf.member.UpdateBussinessMgr.close = function() {
	
	com.jsjn.jnf.member.UpdateBussinessMgr.WINDOW.hide();
	
};

//保存
com.jsjn.jnf.member.UpdateBussinessMgr.update = function() {
	
	var mid =  Ext.getCmp('mid.UpdateBussinessMgr').getValue();
	var mName =  Ext.getCmp('mName.UpdateBussinessMgr').getValue();
	var busLcnsNo = Ext.getCmp('busLcnsNo.UpdateBussinessMgr').getValue();
	var phoneNo = Ext.getCmp('phoneNo.UpdateBussinessMgr').getValue();
	var addr = Ext.getCmp('addr.UpdateBussinessMgr').getValue();
	var status = Ext.getCmp('status.UpdateBussinessMgr').getValue();
	
	if(valueIsEmpty(mid)){
		Ext.Msg.alert('系统提示', '商户号不能为空!');
		return false;
	}
	if(valueIsEmpty(mName)){
		Ext.Msg.alert('系统提示', '商户名称不能为空!');
		return false;
	}
	if(valueIsEmpty(busLcnsNo)){
		Ext.Msg.alert('系统提示', '证件号码不能为空!');
		return false;
	}
	if(valueIsEmpty(phoneNo)){
		Ext.Msg.alert('系统提示', '手机号码不能为空!');
		return false;
	}
	if(valueIsEmpty(addr)){
		Ext.Msg.alert('系统提示', '联系地址不能为空!');
		return false;
	}
	if(valueIsEmpty(status)){
		Ext.Msg.alert('系统提示', '状态不能为空!');
		return false;
	}
	
	var url = '/jnf/businessService.do?method=updateBussinessInfo';
	var param = {
				'mid':mid,
				'mName':mName,
				'busLcnsNo':busLcnsNo,			
				'phoneNo':phoneNo,			
				'addr':addr,			
				'status':status		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.QryBussinessListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "修改成功！", function() {
				com.jsjn.jnf.member.UpdateBussinessMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "修改失败！"+resMsg, function(){});
		}
	
	});
};
