/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.AddBussinessMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.AddBussinessMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.AddBussinessMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.AddBussinessMgr.main method is the beginning of all.
 * com.jsjn.jnf.member.AddBussinessMgr.WINDOW  iscom.jsjn.jnf.member.AddBussinessMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.AddBussinessMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.member.AddBussinessMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.member.AddBussinessMgr", function(){
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('status.AddBussinessMgr'), {
		store : signStatusStore.getStore()
	});	
});

//关闭
com.jsjn.jnf.member.AddBussinessMgr.close = function() {
	
	com.jsjn.jnf.member.AddBussinessMgr.WINDOW.hide();
	
};

//检查联系电话是否合法
com.jsjn.jnf.member.AddBussinessMgr.checkTel = function(){
	var phoneNo = Ext.getCmp('phoneNo.AddBussinessMgr').getValue();
	var patrn=/^(1[3578]\d{9})$/;
	if (!patrn.test(phoneNo)) {
		Ext.Msg.alert('系统提示', '手机号码输入有误!');
		return false;
	}
	return true;
};

//保存
com.jsjn.jnf.member.AddBussinessMgr.save = function() {
	
	var mName =  Ext.getCmp('mName.AddBussinessMgr').getValue();
	var busLcnsNo = Ext.getCmp('busLcnsNo.AddBussinessMgr').getValue();
	var phoneNo = Ext.getCmp('phoneNo.AddBussinessMgr').getValue();
	var addr = Ext.getCmp('addr.AddBussinessMgr').getValue();
	var status = Ext.getCmp('status.AddBussinessMgr').getValue();
	
	
	if(valueIsEmpty(mName)){
		Ext.Msg.alert('系统提示', '商户名称不能为空!');
		return false;
	}
	if(valueIsEmpty(busLcnsNo)){
		Ext.Msg.alert('系统提示', '证件号码不能为空!');
		return false;
	}
	if(valueIsEmpty(phoneNo)){
		Ext.Msg.alert('系统提示', '手机号码不能为空!');
		return false;
	}
	if(valueIsEmpty(addr)){
		Ext.Msg.alert('系统提示', '联系地址不能为空!');
		return false;
	}
	if(valueIsEmpty(status)){
		Ext.Msg.alert('系统提示', '状态不能为空!');
		return false;
	}
	if(!com.jsjn.jnf.member.AddBussinessMgr.checkTel()){
		return false;
	}
	
	var url = '/jnf/businessService.do?method=saveBusinessInfo';
	var param = {'mName':mName,
				'busLcnsNo':busLcnsNo,			
				'phoneNo':phoneNo,			
				'addr':addr,			
				'status':status		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.QryBussinessListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "新增成功！", function() {
				com.jsjn.jnf.member.AddBussinessMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "新增失败！"+resMsg, function(){});
		}
	
	});
};