/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.AuthorityConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.AuthorityConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.AuthorityConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.AuthorityConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.member.AuthorityConfigMgr.WINDOW  iscom.jsjn.jnf.member.AuthorityConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.AuthorityConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.member.AuthorityConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.member.AuthorityConfigMgr",function() {
	Ext.getCmp('grid.AuthorityConfigMgr').getStore().addListener('load',function(store,records,options){
		//业务逻辑
		var mid = com.jsjn.jnf.member.AuthorityConfigMgr.mid;
		//根据商户号获取商户权限
		if(valueIsEmpty(mid)){
			Ext.Msg.alert('系统提示', '商户号不能为空!');
			return false;
		}
		var url = '/jnf/businessService.do?method=findBussinessAuth';
		var param = {
					'mid':mid 
					};
		ajaxLoad(url, param, '', '', '', function(response) {
			var success = Ext.decode(response.responseText).success;
			var resMsg = Ext.decode(response.responseText).resMsg;
			var rows = Ext.decode(response.responseText).root;
			if(success){
				var model = Ext.getCmp('grid.AuthorityConfigMgr').getSelectionModel();
				//id编号从1开始，数组从0开始。需要统一
				var rowsNew = new Array();
				for(var i=0;i<rows.length;i++){
					rowsNew.push(rows[i] - 1);
				}
				model.selectRows(rowsNew);
				
			}else{
				Ext.Msg.alert("系统提示", "查询失败！"+resMsg, function(){});
			}
		
		});
		});
});

com.jsjn.jnf.member.AuthorityConfigMgr.panelInit = function(record){
	com.jsjn.jnf.member.AuthorityConfigMgr.mid = record.data.mid;		//商户编号
	var mName = record.data.mName;		//商户编号
	Ext.getCmp('mName.AuthorityConfigMgr').setValue(mName);
	Ext.getCmp('mid.hidden.AuthorityConfigMgr').setValue(com.jsjn.jnf.member.AuthorityConfigMgr.mid);
	
	Ext.getCmp('grid.AuthorityConfigMgr').getStore().load();
	
	
};

//保存
com.jsjn.jnf.member.AuthorityConfigMgr.save = function(){
	var mid =  Ext.getCmp('mid.hidden.AuthorityConfigMgr').getValue();
	
	var getRows = Ext.getCmp('grid.AuthorityConfigMgr').getSelectionModel().getSelections();
	var roles = new Array();
	//如果不加判断，for循环会执行一次，设置一个空值。
	if(getRows.length != 0){
		for(var i=0;i <getRows.length;i++){
			roles.push(getRows[i].get('id'));
		};
	}
	
	//修改权限配置
	var url = '/jnf/businessService.do?method=updateBussinessAuth';
	var param ={};
	if(getRows.length != 0){
		//新增，修改
		param = {
				'mid':mid,
				'roles':roles
		};
	}else{
		//删除
		param = {
				'mid':mid
		};
	}
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
		var result = Ext.decode(response.responseText).root;
		if(success){
			Ext.Msg.alert("系统提示", "修改商户权限成功！", function(){});
			com.jsjn.jnf.member.AuthorityConfigMgr.close();
		}else{
			Ext.Msg.alert("系统提示", "修改商户权限失败！"+resMsg, function(){});
		}
	
	});
};

//关闭
com.jsjn.jnf.member.AuthorityConfigMgr.close = function(){
	com.jsjn.jnf.member.AuthorityConfigMgr.WINDOW.hide();
};