/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.MemberInfoDetailMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.MemberInfoDetailMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.MemberInfoDetailMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.MemberInfoDetailMgr.main method is the beginning of all.
 * com.jsjn.jnf.member.MemberInfoDetailMgr.WINDOW  iscom.jsjn.jnf.member.MemberInfoDetailMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.MemberInfoDetailMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.member.MemberInfoDetailMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.member.MemberInfoDetailMgr", function() {
	girdStoreAddExceptionEvent('grid.MemberInfoDetailMgr',
	"com.jsjn.jnf.member.MemberInfoDetailMgr");
});

com.jsjn.jnf.member.MemberInfoDetailMgr.panelInit = function(record){
	var custId = record.json.custId;			//客户号
	var custName = record.json.custName;		//客户名称
	var custType = record.json.custType;		//客户类型
	var idType = record.json.idType;			//证件类型
	var idNo = record.json.idNo;				//证件号码
	var insttuId = record.json.insttuId;		//投资人机构号
	var created = record.json.created;			//创建时间
	var modified = record.json.modified;		//最后更新时间
	
	Ext.getCmp('custId.MemberInfoDetailMgr').setValue(custId);
	Ext.getCmp('custName.MemberInfoDetailMgr').setValue(custName);
	Ext.getCmp('custType.MemberInfoDetailMgr').setValue(storeFind(custTypeStore, custType));
	Ext.getCmp('idType.MemberInfoDetailMgr').setValue(storeFind(idTypeStore, idType));
	Ext.getCmp('idNo.MemberInfoDetailMgr').setValue(idNo);
	Ext.getCmp('insttuId.MemberInfoDetailMgr').setValue(insttuId);
	Ext.getCmp('created.MemberInfoDetailMgr').setValue(formatDateToPattern("YYYY-MM-DD",new Date(new Number(created))));
	Ext.getCmp('modified.MemberInfoDetailMgr').setValue(formatDateToPattern("YYYY-MM-DD",new Date(new Number(modified))));
	
	//清空原有的数据
	Ext.getCmp('grid.MemberInfoDetailMgr').getStore().removeAll();
	
	Ext.getCmp('grid.MemberInfoDetailMgr').getStore().load();
};

/**
 * 添加参数
 */
com.jsjn.jnf.member.MemberInfoDetailMgr.addParams = function() {
	var custId = Ext.getCmp('custId.MemberInfoDetailMgr').getValue();	//客户号

	var params = {
			custId : custId
	};
	
	var gStore = Ext.getCmp('grid.MemberInfoDetailMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};


/**
 * 查询绑定卡信息
 */
com.jsjn.jnf.member.MemberInfoDetailMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	com.jsjn.jnf.member.MemberInfoDetailMgr.aid = record.json.aid;//协议号，全局变量
	
	var valid = record.json.valid;//数据是否被篡改
	
	var state = record.json.state;//协议状态
	
	var dataIndex = Ext.getCmp("grid.MemberInfoDetailMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'operator') {
		var operater = "";
		if(valid == false){
			operater += "警告：数据被篡改";
		}
		//正常状态
		if(state == '1'){
			operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.member.MemberInfoDetailMgr.lock();\" style=\"vertical-align:bottom; text-decoration:none\">【冻结】</a>";
		}
		//冻结状态
		if(state == '2'){
			operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.member.MemberInfoDetailMgr.unlock();\" style=\"vertical-align:bottom; text-decoration:none\">【解冻】</a>";
		}
		
		return operater;
	}
	if (dataIndex == 'state') {
		return storeFind(signStatusStore, value);
	}
	if (dataIndex == 'modified') {
		return formatDateToPattern("YYYY-MM-DD",new Date(new Number(value)));
	}
	
	return value;
};

/**
 * 查询
 */
com.jsjn.jnf.member.MemberInfoDetailMgr.Qry = function(){
	//清空原有的数据
	Ext.getCmp('grid.MemberInfoDetailMgr').getStore().removeAll();
	
	Ext.getCmp('grid.MemberInfoDetailMgr').getStore().load();
};

/**
 * 解冻
 */
com.jsjn.jnf.member.MemberInfoDetailMgr.unlock = function(){
	com.jsjn.jnf.member.MemberInfoDetailMgr.update('1');
};

/**
 * 冻结
 */
com.jsjn.jnf.member.MemberInfoDetailMgr.lock = function(){
	com.jsjn.jnf.member.MemberInfoDetailMgr.update('2');
};

/**
 * 更新绑定卡状态
 */
com.jsjn.jnf.member.MemberInfoDetailMgr.update = function(state){
	
	var url = '/jnf/BindCardController.do?method=updateUserCardState';
	var param = {
				'aid':com.jsjn.jnf.member.MemberInfoDetailMgr.aid,
				'state':state
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
		var rsp = Ext.decode(response.responseText).root;
		
		//保存
		if(success){
			Ext.Msg.alert("系统提示", "修改成功！", function(){});
			Ext.getCmp('grid.MemberInfoDetailMgr').getStore().load();
		}else{
			Ext.Msg.alert("系统提示", "修改失败！"+resMsg, function(){});
		}
	
	});
};