/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.member.RegInvestMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.member.RegInvestMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.member.RegInvestMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.member.RegInvestMgr.main method is the beginning of all.
 * com.jsjn.jnf.member.RegInvestMgr.WINDOW  iscom.jsjn.jnf.member.RegInvestMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.member.RegInvestMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.member.RegInvestMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.member.RegInvestMgr", function(){
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('state.RegInvestMgr'), {
		store : memberStateStore.getStore()
	});	
	Ext.apply(Ext.getCmp('idType.RegInvestMgr'), {
		store : idTypeStore.getStore()
	});	
	
});

com.jsjn.jnf.member.RegInvestMgr.panelInit=function(record){
	var mid = record.data.mid;		//商户编号

	Ext.getCmp('mid.RegInvestMgr').setValue(mid);
	
};

//关闭
com.jsjn.jnf.member.RegInvestMgr.close = function() {
	
	com.jsjn.jnf.member.RegInvestMgr.WINDOW.hide();
	
};

//检查联系电话是否合法
com.jsjn.jnf.member.RegInvestMgr.checkTel = function(){
	var phoneNo = Ext.getCmp('mobile.RegInvestMgr').getValue();
	var patrn=/^(1[3578]\d{9})$/;
	if (!patrn.test(phoneNo)) {
		Ext.Msg.alert('系统提示', '手机号码输入有误!');
		return false;
	}
	return true;
};

//保存
com.jsjn.jnf.member.RegInvestMgr.save = function() {
	
	var mid =  Ext.getCmp('mid.RegInvestMgr').getValue();
	var state = Ext.getCmp('state.RegInvestMgr').getValue();
	var idNo = Ext.getCmp('idNo.RegInvestMgr').getValue();
	var insttuId = Ext.getCmp('insttuId.RegInvestMgr').getValue();
	var custName = Ext.getCmp('custName.RegInvestMgr').getValue();
	var mobile = Ext.getCmp('mobile.RegInvestMgr').getValue();
	var idType = Ext.getCmp('idType.RegInvestMgr').getValue();
	var remark = Ext.getCmp('remark.RegInvestMgr').getValue();
	
	
	if(valueIsEmpty(mid)){
		Ext.Msg.alert('系统提示', '商户编号不能为空!');
		return false;
	}
	if(valueIsEmpty(state)){
		Ext.Msg.alert('系统提示', '账号状态不能为空!');
		return false;
	}
	if(valueIsEmpty(idNo)){
		Ext.Msg.alert('系统提示', '证件号码不能为空!');
		return false;
	}
	if(valueIsEmpty(insttuId)){
		Ext.Msg.alert('系统提示', '投资人机构号不能为空!');
		return false;
	}
	if(valueIsEmpty(custName)){
		Ext.Msg.alert('系统提示', '用户名称不能为空!');
		return false;
	}
	if(valueIsEmpty(mobile)){
		Ext.Msg.alert('系统提示', '电话号码不能为空!');
		return false;
	}
	if(valueIsEmpty(idType)){
		Ext.Msg.alert('系统提示', '证件类型不能为空!');
		return false;
	}
	if(!com.jsjn.jnf.member.RegInvestMgr.checkTel()){
		return false;
	}
	
	var url = '/jnf/MemberController.do?method=regInvest';
	var param = {'mId':mid,
				'state':state,			
				'idNo':idNo,			
				'insttuId':insttuId,			
				'custName':custName,	
				'mobile':mobile,	
				'idType':idType,	
				'remark':remark	
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.Msg.alert("系统提示", "新增成功！", function() {
				com.jsjn.jnf.member.RegInvestMgr.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "新增失败！"+resMsg, function(){});
		}
	
	});
};