/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.withhold.QryWithholdInfos's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.withhold.QryWithholdInfos.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.withhold.QryWithholdInfos.prototype.method(); this is object's method'
 * com.jsjn.jnf.withhold.QryWithholdInfos.PANEL is com.jsjn.jnf.withhold.QryWithholdInfos's  Singleton instance object .
 * you can get com.jsjn.jnf.withhold.QryWithholdInfos.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.withhold.QryWithholdInfos'). 
 */
appframe.afterInstance("com.jsjn.jnf.withhold.QryWithholdInfos",function() {
	/*	girdStoreAddExceptionEvent('grid.QryTradeListMgr',
		"com.jsjn.jnf.trade.QryTradeListMgr");*/
		
//	Ext.getCmp('withhold.userName').disable(true);
		//渲染下拉框
	/*	Ext.apply(Ext.getCmp('withhold.mid'), {
			store : com.jsjn.jnf.withhold.QryWithholdInfos.getCom()
		});	*/
		
		Ext.apply(Ext.getCmp('withhold.channel'),{
			store :withhold.getStore()
		});	
		
		Ext.apply(Ext.getCmp('withhold.state'),{
			store :withholdSignState.getStore()
		});	
		
		Ext.apply(Ext.getCmp('withhold.type'),{
			store:signTradeType.getStore()
		});	
});


com.jsjn.jnf.withhold.QryWithholdInfos.addParams = function() {
	var sTime = "";
	var eTime = "";
	var mid = Ext.getCmp('withhold.mid').getValue();	//商户号
	var custName = Ext.getCmp('withhold.custName').getValue();	//商户名称
	var insttuName = Ext.getCmp('withhold.insttuName').getValue(); //状态
	var loanNo = Ext.getCmp('withhold.loanNo').getValue(); //状态
	var startTime = Ext.getCmp('withhold.startTime').getValue(); //状态
	var endTime = Ext.getCmp('withhold.endTime').getValue(); //状态
	var user =  Ext.getCmp('withhold.userName').getValue(); 
	if(startTime!=""&&startTime!="undefined"){
		sTime   =formatDateToPattern("YYYY-MM-DD hh:mm:ss",new Date(startTime));
	}
	if(endTime!=""&&endTime!="undefined"){
		 eTime = formatDateToPattern("YYYY-MM-DD hh:mm:ss",new Date(endTime));
	}
		
	var state =  Ext.getCmp('withhold.state').getValue();
	var type = Ext.getCmp('withhold.type').getValue(); //状态
	var channel = Ext.getCmp('withhold.channel').getValue(); //状态
	var params = {
		mid : mid,
		custName : custName,
		insttuName : insttuName,
		loanNo:loanNo,
		startTime:sTime,
		endTime:eTime,
		type:type,
		channel:channel,
		state:state,
		insttuId:user
	};
	var gStore = Ext.getCmp('grid.withhodInfo').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.withhold.QryWithholdInfos.qryUserName = function(mid){
	   var params = {
			mid : mid
		};
		var gStore = Ext.getCmp('withhold.userName').getStore();
		// 判断grid的store中存在查询参数和查询结果
		if (undefined != gStore && gStore.getCount() > 0) {
			gStore.removeAll(); // 清空表格store中的查询参数
		}
		gStore.baseParams = params;
};

com.jsjn.jnf.withhold.QryWithholdInfos.selectMid = function(combo, record, index){
//	Ext.getCmp('withhold.userName').disable(false);
	com.jsjn.jnf.withhold.QryWithholdInfos.qryUserName(record.data.mid);
	Ext.getCmp('withhold.userName').getStore().load();
};
com.jsjn.jnf.withhold.QryWithholdInfos.gridRender =function(value,
		cellmeta, record, rowIndex, columnIndex, store){
	var dataIndex = Ext.getCmp("grid.withhodInfo").getColumnModel()
	.getDataIndex(columnIndex);
if (dataIndex == 'cplsh') {
return rowIndex + 1;
}
if (dataIndex == 'operator') {
var operater = "";
operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.withhold.QryWithholdInfos.detail();\" style=\"vertical-align:bottom; text-decoration:none\">【详&nbsp&nbsp&nbsp情】</a>";
return operater;
}
if (dataIndex == 'created') {
return formatDateToPattern("YYYY-MM-DD hh:mm:ss",new Date(value));
}
if (dataIndex == 'type') {
		return storeFind(signTradeType, value);
}
if (dataIndex == 'state') {
	return storeFind(withholdSignState, value);
}
if (dataIndex == 'channel') {
	return storeFind(withhold, value);
}
return value;
};
/**
 * 查询协议
 */
com.jsjn.jnf.withhold.QryWithholdInfos.query = function(button,
		event){
	com.jsjn.jnf.withhold.QryWithholdInfos.addParams();
	Ext.getCmp('grid.withhodInfo').getStore().load();
};
/**
 * 重置
 */
com.jsjn.jnf.withhold.QryWithholdInfos.reset = function(button,
		event){
	Ext.getCmp('form.Withhold').getForm().reset();
};


com.jsjn.jnf.withhold.QryWithholdInfos.detail = function(){
	var win = appframe.getInstance("com.jsjn.jnf.withhold.QryWithholdDetails");
	var record = Ext.getCmp('grid.withhodInfo').getSelectionModel().getSelected();
	com.jsjn.jnf.withhold.QryWithholdDetails.detail(record);
	win.show();
};
/*com.jsjn.jnf.withhold.QryWithholdInfos.getCom = function(){
	var store = "";
	Ext.Ajax.request({
	    method : "POST",
	    url : appConfig.baseUrl + '/qryWithholdInfos.do?method=getCommercial',
	    success : function(response) {
	        var result = Ext.decode(response.responseText);
	        store = result.root;
	    }
	});
	return store;
	var xhreader = new Ext.data.JsonReader({
		id : "id"
	}, [ {
		mapping : "mid",
		type : "string",
		name : "mid"
	}, {
		mapping : "mName",
		type : "string",
		name : "mName"
	} ]);

	idTypeStore = {};
	idTypeStore.getStore = function() {
	if (idTypeStore.data == undefined || idTypeStore.data == '') {
	var data = load_local_ggxh_data('ID_TYPE');
	idTypeStore.data = new Ext.data.Store({
	autoLoad : true,
	reader : xhreader
	});
	idTypeStore.data.loadData(data);
	}
	return idTypeStore.data;
	};
};*/


