/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.AddChannelBankConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.AddChannelBankConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.AddChannelBankConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.AddChannelBankConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.AddChannelBankConfigMgr.WINDOW  iscom.jsjn.jnf.config.AddChannelBankConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.AddChannelBankConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.AddChannelBankConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.AddChannelBankConfigMgr", function(){
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('channelId.AddChannelBankConfigMgr'), {
		store : withholdChannelStore.getStore()
	});

});

/**
 * 新增
 */
com.jsjn.jnf.config.AddChannelBankConfigMgr.save = function(){
	
	var channelId =  Ext.getCmp('channelId.AddChannelBankConfigMgr').getValue();
	var jnBankCode = Ext.getCmp('jnBankCode.AddChannelBankConfigMgr').getValue();
	var maxAmount = Ext.getCmp('maxAmount.AddChannelBankConfigMgr').getValue();
	var bankName = Ext.getCmp('bankName.AddChannelBankConfigMgr').getValue();
	var channelBankCode = Ext.getCmp('channelBankCode.AddChannelBankConfigMgr').getValue();
	var maxAmountDay = Ext.getCmp('maxAmountDay.AddChannelBankConfigMgr').getValue();
	
	if(valueIsEmpty(channelId)){
		Ext.Msg.alert('系统提示', '渠道名称不能为空!');
		return false;
	}
	if(valueIsEmpty(jnBankCode)){
		Ext.Msg.alert('系统提示', '金农银行CODE不能为空!');
		return false;
	}
	if(valueIsEmpty(bankName)){
		Ext.Msg.alert('系统提示', '银行名称不能为空!');
		return false;
	}
	if(valueIsEmpty(channelBankCode)){
		Ext.Msg.alert('系统提示', '渠道银行CODE不能为空!');
		return false;
	}
	
	var url = 'jnf/channelBankService.do?method=addBankInfo';
	var param = {'channelId':channelId,
				'jnBankCode':jnBankCode,			
				'maxAmount':maxAmount,			
				'bankName':bankName,	
				'channelBankCode':channelBankCode,	
				'maxAmountDay':maxAmountDay	
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.ChannelBankConfigMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "新增成功！", function() {
				com.jsjn.jnf.config.AddChannelBankConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "新增失败！"+resMsg, function(){});
		}
	
	});
	
};

/**
 * 关闭
 */
com.jsjn.jnf.config.AddChannelBankConfigMgr.close = function(){
	
	com.jsjn.jnf.config.AddChannelBankConfigMgr.WINDOW.hide();
};