/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.AddConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.AddConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.AddConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.AddConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.AddConfigMgr.WINDOW  iscom.jsjn.jnf.config.AddConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.AddConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.AddConfigMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.config.AddConfigMgr", function(){
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('feeType.AddConfigMgr'), {
		store : feeTypeStore.getStore()
	});	
});

/**
 * 新增
 */
com.jsjn.jnf.config.AddConfigMgr.save = function(){
	
	var mid =  Ext.getCmp('mid.AddConfigMgr').getValue();
	var orgNo = Ext.getCmp('orgNo.AddConfigMgr').getValue();
	var feeType = Ext.getCmp('feeType.AddConfigMgr').getValue();
	var fee = Ext.getCmp('fee.AddConfigMgr').getValue();
	var startTime = Ext.getCmp('startTime.AddConfigMgr').getRawValue();
	var endTime = Ext.getCmp('endTime.AddConfigMgr').getRawValue();
	
	
	if(valueIsEmpty(mid)){
		Ext.Msg.alert('系统提示', '商户号不能为空!');
		return false;
	}
	if(valueIsEmpty(orgNo)){
		Ext.Msg.alert('系统提示', '机构码不能为空!');
		return false;
	}
	if(valueIsEmpty(feeType)){
		Ext.Msg.alert('系统提示', '费用种类不能为空!');
		return false;
	}
	if(valueIsEmpty(fee)){
		Ext.Msg.alert('系统提示', '费用不能为空!');
		return false;
	}
	if(valueIsEmpty(startTime)){
		Ext.Msg.alert('系统提示', '开始实际不能为空!');
		return false;
	}
	if(valueIsEmpty(endTime)){
		Ext.Msg.alert('系统提示', '结束时间不能为空!');
		return false;
	}
	if(startTime > endTime){
		Ext.Msg.alert('系统提示', '开始时间不能大于结束时间!');
		return false;
	}
	
	var url = 'jnf/feeConfigService.do?method=addFeeConfig';
	var param = {'mid':mid,
				'orgNo':orgNo,			
				'fee':fee,			
				'feeType':feeType,			
				'startTime':startTime,		
				'endTime':endTime		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.FeeConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "新增成功！", function() {
				com.jsjn.jnf.config.AddConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "新增失败！"+resMsg, function(){});
		}
	
	});
	
};

/**
 * 关闭
 */
com.jsjn.jnf.config.AddConfigMgr.close = function(){
	
	com.jsjn.jnf.config.AddConfigMgr.WINDOW.hide();
};