/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.AddDictConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.AddDictConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.AddDictConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.AddDictConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.AddDictConfigMgr.WINDOW  iscom.jsjn.jnf.config.AddDictConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.AddDictConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.AddDictConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.AddDictConfigMgr", function(){
	
});

/**
 * 新增
 */
com.jsjn.jnf.config.AddDictConfigMgr.save = function(){
	
	var value =  Ext.getCmp('value.AddDictConfigMgr').getValue();
	var testValue =  Ext.getCmp('testValue.AddDictConfigMgr').getValue();
	var type = Ext.getCmp('type.AddDictConfigMgr').getValue();
	var label = Ext.getCmp('label.AddDictConfigMgr').getValue();
	var desc = Ext.getCmp('desc.AddDictConfigMgr').getValue();
	
	
	if(valueIsEmpty(value)){
		Ext.Msg.alert('系统提示', '正式环境字典值不能为空!');
		return false;
	}
	if(valueIsEmpty(testValue)){
		Ext.Msg.alert('系统提示', '测试环境字典值不能为空!');
		return false;
	}
	if(valueIsEmpty(label)){
		Ext.Msg.alert('系统提示', '字典标签不能为空!');
		return false;
	}
	if(valueIsEmpty(type)){
		Ext.Msg.alert('系统提示', '字典类型不能为空!');
		return false;
	}
	if(valueIsEmpty(desc)){
		Ext.Msg.alert('系统提示', '字典类型不能为空!');
		return false;
	}
	
	var url = 'jnf/dictService.do?method=addDictInfo';
	var param = {
				'value':value,
				'testValue':testValue,
				'label':label,			
				'type':type,			
				'desc':desc		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.DictConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "新增成功！", function() {
				com.jsjn.jnf.config.AddDictConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "新增失败！"+resMsg, function(){});
		}
	
	});
	
};

/**
 * 关闭
 */
com.jsjn.jnf.config.AddDictConfigMgr.close = function(){
	
	com.jsjn.jnf.config.AddDictConfigMgr.WINDOW.hide();
};