/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.ChannelBankConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.ChannelBankConfigMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.ChannelBankConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.ChannelBankConfigMgr.PANEL is com.jsjn.jnf.config.ChannelBankConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.ChannelBankConfigMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.config.ChannelBankConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.ChannelBankConfigMgr",function() {
		
	//渲染下拉框
	Ext.apply(Ext.getCmp('channelId.ChannelBankConfigMgr'), {
		store : withholdChannelStore.getStore()
	});	
	
});

com.jsjn.jnf.config.ChannelBankConfigMgr.addParams = function() {
	var channelId = Ext.getCmp('channelId.ChannelBankConfigMgr').getValue();	//选项代码
	var bankName = Ext.getCmp('bankName.ChannelBankConfigMgr').getValue();	//选项代码
	
	var params = {
			'channelId' : channelId,
			'bankName' : bankName
	};
	
	var gStore = Ext.getCmp('grid.ChannelBankConfigMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.config.ChannelBankConfigMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var dataIndex = Ext.getCmp("grid.ChannelBankConfigMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	
	if (dataIndex == 'channelId') {
		return storeFind(withholdChannelStore, value);
	}
	
	if (dataIndex == 'maxAmount') {
		if("" == value){
			return "不限";
		}
		return formatMoney(value);
	}
	
	if (dataIndex == 'maxAmountDay') {
		if("" == value){
			return "不限";
		}
		return formatMoney(value);
	}
	
	return value;
};

/**
 * 点击查询按钮
 */
com.jsjn.jnf.config.ChannelBankConfigMgr.btnQuery = function(){
	
	com.jsjn.jnf.config.ChannelBankConfigMgr.addParams();
	
	Ext.getCmp('grid.ChannelBankConfigMgr').getStore().load();
	
};

/**
 * 新增渠道银行信息
 */
com.jsjn.jnf.config.ChannelBankConfigMgr.btnAdd = function(){
	
	var win = appframe.getInstance("com.jsjn.jnf.config.AddChannelBankConfigMgr");

	win.show();
	
	//清空新增 信息
	Ext.getCmp('form.AddChannelBankConfigMgr').getForm().reset();
};

/**
 * 修改渠道银行信息
 */
com.jsjn.jnf.config.ChannelBankConfigMgr.btnUpdate = function(){
	
	var record = Ext.getCmp('grid.ChannelBankConfigMgr').getSelectionModel().getSelected();
	if(record=="undefined"||record==null){
		 Ext.MessageBox.alert('提示', '请选中你要操作的数据');
		return;
	}
	var win = appframe.getInstance("com.jsjn.jnf.config.UpdateChannelBankConfigMgr");
	
	win.show();
	
	com.jsjn.jnf.config.UpdateChannelBankConfigMgr.panelInit(record);
	
};

/**
 * 删除渠道银行信息
 */
com.jsjn.jnf.config.ChannelBankConfigMgr.btnDelete = function(){
	
   	var record = Ext.getCmp('grid.ChannelBankConfigMgr').getSelectionModel().getSelected();
	if(record=="undefined"||record==null){
		 Ext.MessageBox.alert('提示', '请选中你要操作的数据');
		return;
	}
	Ext.MessageBox.confirm("提示", '您确定要删除该银行吗？', function(btn) {
        if (btn == 'yes') {
        	var channelId = record.data.channelId;
        	var jnBankCode = record.data.jnBankCode;
        	var url = 'jnf/channelBankService.do?method=delBankInfo';
        	var param = {
        				'channelId':channelId,
        				'jnBankCode':jnBankCode
        				};
        	ajaxLoad(url, param, '', '', '', function(response) {
        		var success = Ext.decode(response.responseText).success;
        		var resMsg = Ext.decode(response.responseText).resMsg;
//        		var temp = Ext.decode(response.responseText).root;
        		if(success){
        			Ext.getCmp('grid.ChannelBankConfigMgr')
        			.getStore().reload();
        			Ext.Msg.alert("系统提示", "删除成功！", function() {
        			});
        		}else{
        			Ext.Msg.alert("系统提示", "删除失败！"+resMsg, function(){});
        		}
        	
        	});
        }
    });
	
};