/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.DictConfigListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.DictConfigListMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.DictConfigListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.DictConfigListMgr.PANEL is com.jsjn.jnf.config.DictConfigListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.DictConfigListMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.config.DictConfigListMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.DictConfigListMgr",function() {
//		girdStoreAddExceptionEvent('grid.DictConfigListMgr',
//		"com.jsjn.jnf.config.DictConfigListMgr");
		
});

com.jsjn.jnf.config.DictConfigListMgr.addParams = function() {
	
	var params = {};
	
	var gStore = Ext.getCmp('grid.DictConfigListMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.config.DictConfigListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var dataIndex = Ext.getCmp("grid.DictConfigListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'value') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	if (dataIndex == 'testValue') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	if (dataIndex == 'label') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	if (dataIndex == 'type') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	if (dataIndex == 'desc') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	
	return value;
};


/**
 * 点击查询按钮
 */
com.jsjn.jnf.config.DictConfigListMgr.btnAdd = function(){
	
	var win = appframe.getInstance("com.jsjn.jnf.config.AddDictConfigMgr");

	win.show();
	
	//清空新增 信息
	Ext.getCmp('form.AddDictConfigMgr').getForm().reset();
};

/**
 * 修改
 */
com.jsjn.jnf.config.DictConfigListMgr.btnUpdate  = function(){
	var record = Ext.getCmp('grid.DictConfigListMgr').getSelectionModel().getSelected();
	if(record=="undefined"||record==null){
		 Ext.MessageBox.alert('提示', '请选中你要操作的数据');
		return;
	}
	var win = appframe.getInstance("com.jsjn.jnf.config.UpdateDictConfigMgr");
	
	win.show();
	
	com.jsjn.jnf.config.UpdateDictConfigMgr.panelInit(record);
	
};
