/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.MenuConfigListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.MenuConfigListMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.MenuConfigListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.MenuConfigListMgr.PANEL is com.jsjn.jnf.config.MenuConfigListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.MenuConfigListMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.config.MenuConfigListMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.MenuConfigListMgr",function() {
	
//		girdStoreAddExceptionEvent('grid.MenuConfigListMgr',
//		"com.jsjn.jnf.config.MenuConfigListMgr");
		
});


com.jsjn.jnf.config.MenuConfigListMgr.addParams = function() {
	var menuCde = Ext.getCmp('menuCde.MenuConfigListMgr').getValue();	//选项代码
	
	var params = {
			'menuCde' : menuCde
	};
	
	var gStore = Ext.getCmp('grid.MenuConfigListMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.config.MenuConfigListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var dataIndex = Ext.getCmp("grid.MenuConfigListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'operator') {
		var operater = "";
		operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.config.MenuConfigListMgr.update();\" style=\"vertical-align:bottom; text-decoration:none\">【修改】</a>";
		operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.config.MenuConfigListMgr.del();\" style=\"vertical-align:bottom; text-decoration:none\">【删除】</a>";
		return operater;
	}
	
	return value;
};

/**
 * 点击查询按钮
 */
com.jsjn.jnf.config.MenuConfigListMgr.btnQuery = function(){
	
	com.jsjn.jnf.config.MenuConfigListMgr.addParams();

	Ext.getCmp('grid.MenuConfigListMgr').getStore().load();
	
};

/**
 * 新增计费种类信息
 */
com.jsjn.jnf.config.MenuConfigListMgr.btnAdd = function(){
	
	var win = appframe.getInstance("com.jsjn.jnf.config.AddMenuConfigMgr");

	win.show();
	
	//清空新增 信息
	Ext.getCmp('form.AddMenuConfigMgr').getForm().reset();
};

/**
 * 修改计费种类信息
 */
com.jsjn.jnf.config.MenuConfigListMgr.btnUpdate = function(){
	
	var record = Ext.getCmp('grid.MenuConfigListMgr').getSelectionModel().getSelected();
	if(record=="undefined"||record==null){
		 Ext.MessageBox.alert('提示', '请选中你要操作的数据');
		return;
	}
	var win = appframe.getInstance("com.jsjn.jnf.config.UpdateMenuConfigMgr");
	
	win.show();
	
	com.jsjn.jnf.config.UpdateMenuConfigMgr.panelInit(record);
	
};

/**
 * 删除该笔计费种类信息
 */
com.jsjn.jnf.config.MenuConfigListMgr.btnDelete  = function(){
	
	var record = Ext.getCmp('grid.MenuConfigListMgr').getSelectionModel().getSelected();
	if(record=="undefined"||record==null){
		 Ext.MessageBox.alert('提示', '请选中你要操作的数据');
		return;
	}
	Ext.MessageBox.confirm("提示", '您确定要删除该字典配置信息吗？', function(btn) {
        if (btn == 'yes') {
        	
        	var menuCde = record.data.menuCde;
        	var menuKey = record.data.menuKey;
        	var url = 'jnf/menuConfigService.do?method=delMenu';
        	var param = {
        				'menuCde':menuCde,
        				'menuKey':menuKey
        				};
        	ajaxLoad(url, param, '', '', '', function(response) {
        		var success = Ext.decode(response.responseText).success;
        		var resMsg = Ext.decode(response.responseText).resMsg;
//        		var temp = Ext.decode(response.responseText).root;
        		if(success){
        			Ext.getCmp('grid.MenuConfigListMgr')
        			.getStore().reload();
        			Ext.Msg.alert("系统提示", "删除成功！", function() {
        			});
        		}else{
        			Ext.Msg.alert("系统提示", "删除失败！"+resMsg, function(){});
        		}
        	
        	});
        }
    });
	
};
com.jsjn.jnf.config.MenuConfigListMgr.btnClearCache = function(){
	Ext.Ajax.request({
		method : "POST",
		url : appConfig.baseUrl
				+ '/jnf/menuConfigService.do?method=clearCache',
				success : function(response) {
					var result = Ext.decode(response.responseText);
					if(result.success){
						alert(result.data);
					}else{
						alert(result.data);
					}
			}
	});
};
com.jsjn.jnf.config.MenuConfigListMgr.btnClear= function(){
	
	
	//清空新增 信息
	Ext.getCmp('form.AddMenuConfigMgr').getForm().reset();
};