/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.UpdateMenuConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.UpdateMenuConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.UpdateMenuConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.UpdateMenuConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.UpdateMenuConfigMgr.WINDOW  iscom.jsjn.jnf.config.UpdateMenuConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.UpdateMenuConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.UpdateMenuConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.UpdateMenuConfigMgr", function(){
	
});

//回显字典表
com.jsjn.jnf.config.UpdateMenuConfigMgr.panelInit=function(record){
	
	var menuCde = record.data.menuCde;			//字典值
	var menuKey = record.data.menuKey;			//字典标签
	var menuValue = record.data.menuValue;			//字典类型
	var menuSort = record.data.menuSort;			//字典说明

	Ext.getCmp('menuCde.UpdateMenuConfigMgr').setValue(menuCde);
	Ext.getCmp('menuKey.UpdateMenuConfigMgr').setValue(menuKey);
	Ext.getCmp('menuValue.UpdateMenuConfigMgr').setValue(menuValue);
	Ext.getCmp('menuSort.UpdateMenuConfigMgr').setValue(menuSort);
	
};


/**
 * 修改
 */
com.jsjn.jnf.config.UpdateMenuConfigMgr.save = function(){
	
	var menuCde =  Ext.getCmp('menuCde.UpdateMenuConfigMgr').getValue();
	var menuKey = Ext.getCmp('menuKey.UpdateMenuConfigMgr').getValue();
	var menuValue = Ext.getCmp('menuValue.UpdateMenuConfigMgr').getValue();
	var menuSort = Ext.getCmp('menuSort.UpdateMenuConfigMgr').getValue();
	
	if(valueIsEmpty(menuCde)){
		Ext.Msg.alert('系统提示', '选项代码不能为空!');
		return false;
	}
	if(valueIsEmpty(menuKey)){
		Ext.Msg.alert('系统提示', '选项序号不能为空!');
		return false;
	}
	if(valueIsEmpty(menuValue)){
		Ext.Msg.alert('系统提示', '字典标签不能为空!');
		return false;
	}
	if(valueIsEmpty(menuSort)){
		Ext.Msg.alert('系统提示', '字典类型不能为空!');
		return false;
	}
	
	var url = 'jnf/menuConfigService.do?method=updateMenu';
	var param = {'menuCde':menuCde,
				'menuKey':menuKey,			
				'menuValue':menuValue,			
				'menuSort':menuSort		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.MenuConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "修改成功！", function() {
				com.jsjn.jnf.config.UpdateMenuConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "修改失败！"+resMsg, function(){});
		}
	
	});
	
};

/**
 * 关闭
 */
com.jsjn.jnf.config.UpdateMenuConfigMgr.close = function(){
	
	com.jsjn.jnf.config.UpdateMenuConfigMgr.WINDOW.hide();
};