/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.UpdateConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.UpdateConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.UpdateConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.UpdateConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.UpdateConfigMgr.WINDOW  iscom.jsjn.jnf.config.UpdateConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.UpdateConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.UpdateConfigMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.config.UpdateConfigMgr", function() {
	
	//渲染下拉框
	Ext.apply(Ext.getCmp('feeType.UpdateConfigMgr'), {
		store : feeTypeStore.getStore()
	});	
	
	reSetComboValue(['feeType.UpdateConfigMgr']);
});

//回显理财详细信息
com.jsjn.jnf.config.UpdateConfigMgr.panelInit=function(record){
	
	com.jsjn.jnf.config.UpdateConfigMgr.id = record.data.id;			//序号
	var mid = record.data.mid;			//商户编号
	var orgNo = record.data.orgNo;		//机构码
	var feeType = record.data.feeType;	//计费种类
	var fee = record.data.fee;			//费用
	var startTime = record.data.startTime;	//开始时间
	var endTime = record.data.endTime;	//结束时间

	Ext.getCmp('mid.UpdateConfigMgr').setValue(mid);
	Ext.getCmp('orgNo.UpdateConfigMgr').setValue(orgNo);
	Ext.getCmp('feeType.UpdateConfigMgr').setValue(feeType);
	Ext.getCmp('fee.UpdateConfigMgr').setValue(fee);
	Ext.getCmp('startTime.UpdateConfigMgr').setValue(startTime.substr(0,10));
	Ext.getCmp('endTime.UpdateConfigMgr').setValue(endTime.substr(0,10));
	
};

//关闭
com.jsjn.jnf.config.UpdateConfigMgr.close = function() {
	
	com.jsjn.jnf.config.UpdateConfigMgr.WINDOW.hide();
	
};

//保存
com.jsjn.jnf.config.UpdateConfigMgr.save = function() {
	
	var mid =  Ext.getCmp('mid.UpdateConfigMgr').getValue();
	var orgNo = Ext.getCmp('orgNo.UpdateConfigMgr').getValue();
	var feeType = Ext.getCmp('feeType.UpdateConfigMgr').getValue();
	var fee = Ext.getCmp('fee.UpdateConfigMgr').getValue();
	var startTime = Ext.getCmp('startTime.UpdateConfigMgr').getRawValue();
	var endTime = Ext.getCmp('endTime.UpdateConfigMgr').getRawValue();
	
	if(valueIsEmpty(mid)){
		Ext.Msg.alert('系统提示', '商户号不能为空!');
		return false;
	}
	if(valueIsEmpty(orgNo)){
		Ext.Msg.alert('系统提示', '机构码不能为空!');
		return false;
	}
	if(valueIsEmpty(feeType)){
		Ext.Msg.alert('系统提示', '费用种类不能为空!');
		return false;
	}
	if(valueIsEmpty(fee)){
		Ext.Msg.alert('系统提示', '费用不能为空!');
		return false;
	}
	if(valueIsEmpty(startTime)){
		Ext.Msg.alert('系统提示', '开始实际不能为空!');
		return false;
	}
	if(valueIsEmpty(endTime)){
		Ext.Msg.alert('系统提示', '结束时间不能为空!');
		return false;
	}
	if(startTime > endTime){
		Ext.Msg.alert('系统提示', '开始时间不能大于结束时间!');
		return false;
	}
	
	var url = 'jnf/feeConfigService.do?method=updateFeeConfig';
	var param = {
				'id':com.jsjn.jnf.config.UpdateConfigMgr.id,
				'mid':mid,
				'orgNo':orgNo,			
				'fee':fee,			
				'feeType':feeType,			
				'startTime':startTime,		
				'endTime':endTime		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.FeeConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "修改成功！", function() {
				com.jsjn.jnf.config.UpdateConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "修改失败！"+resMsg, function(){});
		}
	
	});
};