/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.config.UpdateDictConfigMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.config.UpdateDictConfigMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.config.UpdateDictConfigMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.config.UpdateDictConfigMgr.main method is the beginning of all.
 * com.jsjn.jnf.config.UpdateDictConfigMgr.WINDOW  iscom.jsjn.jnf.config.UpdateDictConfigMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.config.UpdateDictConfigMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.config.UpdateDictConfigMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.config.UpdateDictConfigMgr", function(){
	
});

//回显字典表
com.jsjn.jnf.config.UpdateDictConfigMgr.panelInit=function(record){
	
	com.jsjn.jnf.config.UpdateDictConfigMgr.id = record.data.id;			//序号
	var value = record.data.value;			//正式环境字典值
	var testValue = record.data.testValue;			//测试环境字典值
	var label = record.data.label;			//字典标签
	var type = record.data.type;			//字典类型
	var desc = record.data.desc;			//字典说明
	//var sort = record.data.sort;			//排序
	//var parentId = record.data.parentId;	//父节点

	Ext.getCmp('id.UpdateDictConfigMgr').setValue(record.data.id);
	Ext.getCmp('value.UpdateDictConfigMgr').setValue(value);
	Ext.getCmp('testValue.UpdateDictConfigMgr').setValue(testValue);
	Ext.getCmp('label.UpdateDictConfigMgr').setValue(label);
	Ext.getCmp('type.UpdateDictConfigMgr').setValue(type);
	Ext.getCmp('desc.UpdateDictConfigMgr').setValue(desc);
	
};


/**
 * 修改
 */
com.jsjn.jnf.config.UpdateDictConfigMgr.save = function(){
	
	var value =  Ext.getCmp('value.UpdateDictConfigMgr').getValue();
	var testValue =  Ext.getCmp('testValue.UpdateDictConfigMgr').getValue();
	var type = Ext.getCmp('type.UpdateDictConfigMgr').getValue();
	var label = Ext.getCmp('label.UpdateDictConfigMgr').getValue();
	var desc = Ext.getCmp('desc.UpdateDictConfigMgr').getValue();
	
	
	if(valueIsEmpty(value)){
		Ext.Msg.alert('系统提示', '正式环境字典值不能为空!');
		return false;
	}
	if(valueIsEmpty(testValue)){
		Ext.Msg.alert('系统提示', '测试环境字典值不能为空!');
		return false;
	}
	if(valueIsEmpty(label)){
		Ext.Msg.alert('系统提示', '字典中文标签不能为空!');
		return false;
	}
	if(valueIsEmpty(type)){
		Ext.Msg.alert('系统提示', '字典英文类型不能为空!');
		return false;
	}
	if(valueIsEmpty(desc)){
		Ext.Msg.alert('系统提示', '字典备注说明不能为空!');
		return false;
	}
	
	var url = 'jnf/dictService.do?method=updateDictInfo';
	var param = {
				'id':com.jsjn.jnf.config.UpdateDictConfigMgr.id,
				'value':value,
				'testValue':testValue,
				'label':label,			
				'type':type,			
				'desc':desc		
				};
	ajaxLoad(url, param, '', '', '', function(response) {
		var success = Ext.decode(response.responseText).success;
		var resMsg = Ext.decode(response.responseText).resMsg;
//		var temp = Ext.decode(response.responseText).root;
		if(success){
			Ext.getCmp('grid.DictConfigListMgr')
				.getStore().reload();
			Ext.Msg.alert("系统提示", "修改成功！", function() {
				com.jsjn.jnf.config.UpdateDictConfigMgr
					.WINDOW.hide();
					});
		}else{
			Ext.Msg.alert("系统提示", "修改失败！"+resMsg, function(){});
		}
	
	});
	
};

/**
 * 关闭
 */
com.jsjn.jnf.config.UpdateDictConfigMgr.close = function(){
	
	com.jsjn.jnf.config.UpdateDictConfigMgr.WINDOW.hide();
};