/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo.prototype.method(); this is object's method'
 * com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo.PANEL is com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo's  Singleton instance object .
 * you can get com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo'). 
 */
appframe.afterInstance("com.jsjn.jnf.withhold.sign.query.LoadWithholdInfo",function() {
	
	//如果是ie8，手动加载css样式
    if(Ext.isIE8){
    	appframe.loadCss("/js/webuploader/webuploader.css","webuploader");
    	appframe.loadCss("/js/webuploader/style.css","style");
    	appframe.loadCss("/js/webuploader/style_back.css","style_back");
    	appframe.loadCss("/js/webuploader/style_other.css","style_other");
    	appframe.loadCss("/com/jsjn/jnf/withhold/sign/add/form/myStyle.css","myStyle");
    }
	
});