/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo's method: Javascript class
 * static method be used as ExtJs's event method handler,like
 * 'com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.method(); this is Class
 * static method' Javasctipt object method be used as get or set object's
 * properties,like
 * 'com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.prototype.method(); this
 * is object's method' com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.main
 * method is the beginning of all.
 * com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.WINDOW
 * iscom.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo's Singleton instance
 * object . you can get com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.WINDOW
 * reference by
 * appfram.getInstance('com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo').
 */
appframe.afterInstance("com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo",
		function() {

		});

com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.winInit = function() {
	$.ajax({
		url : 'jnf/withhold.do?method=querySignTempInfoById',// 跳转到 action
		data : {
			signRecordId : appConfig.Param.tempParam.split("|")[0]
		},
		type : 'post',
		cache : false,
		dataType : 'json',
		success : function(data) {
			if (data.success == true) {
				Ext.getCmp('contNo.ViewWithHoldInfo')
						.setValue(data.data.contNo);
				Ext.getCmp('custName.ViewWithHoldInfo')
						.setValue(data.data.custName);
				Ext.getCmp('idNo.ViewWithHoldInfo').setValue(data.data.idNo);
				Ext.getCmp('cardNo.ViewWithHoldInfo')
						.setValue(data.data.cardNo);
				Ext.getCmp('mobile.ViewWithHoldInfo')
						.setValue(data.data.mobile);
				var isBatchPay = data.data.isBatchPay == 'Y' ? '是' : '否';
				Ext.getCmp('isBatchPay.ViewWithHoldInfo').setValue(isBatchPay);
				Ext.getCmp('payStartDay.ViewWithHoldInfo')
						.setValue(data.data.payStartDay);
				// 回显渠道中文
				com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo
						.showChannel(data.data.channel);

				// 回显示图片信息--身份证信息
				var channelSign = data.data.channelSign;
				var array = data.data.idFiles.split("|");
				var front = array[0];
				var back = array[1];
				com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.loadImage(
						front, "front.ViewWithHoldInfo", '60%', '80%');
				com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.loadImage(
						back, "back.ViewWithHoldInfo", '60%', '80%');
				com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.loadFiles(data.data.signFiles,'other.ViewWithHoldInfo', '60%', '80%');

				// 查询卡bin
				if (data.data.cardNo != '' || data.data.cardNo != null) {
					// ajax请求
					$.ajax({
						url : 'jnf/withhold.do?method=cardInfoQuery',// 跳转到
																		// action
						data : {
							cardNo : data.data.cardNo
						},
						type : 'post',
						cache : false,
						dataType : 'json',
						success : function(data) {
							if (data.resCode == "000000") {
								// 查询成功
								var kind = data.cardKind == '0' ? "借记卡" : "信用卡";
								// $("#bankName").val(data.bankName+" | "+kind);
								Ext.getCmp('bankName.ViewWithHoldInfo')
										.setValue(data.bankName + " | " + kind);

							}
						},
						error : function() {
							Ext.Msg.alert('系统提示', data.resMsg);
						}
					});
				}

			} else {
				Ext.Msg.alert('系统提示', '查询出错！');
			}
		},
		error : function() {
			Ext.Msg.alert('系统提示', data.resMsg);
		}
	});
};

com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.showChannel = function(key) {
	$.ajax({
				url : "jnf/withhold.do?method=findAllMenuByCode",
				data : {
					menuCde : 'WITHHOLD_CHANNEL'
				},
				type : "post",
				datatype : "json",
				async : false,
				success : function(data) {
					var rsp = eval('(' + data + ')');
					if (rsp) {
						var array = rsp.root;
						for (var i = 0; i < array.length; i++) {
							if (key == array[i].menuKey) {
								Ext.getCmp('channel.ViewWithHoldInfo')
										.setValue(array[i].menuValue);
								return;
							}
						}
					}

				}
			});
};

com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.loadImage = function(url,
		position, width, height) {
	var file = url.split("#");
	var filePath = file.pop();
	var fileName = file.shift();
	var images = "<div style=\"padding-left:40%\"><image style=\"width:"
			+ width
			+ ";height:"
			+ height
			+ "\" src=fileServer.do?method=getfile&filepath="
			+ filePath
			+ " onclick='com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.showImage(\""
			+ filePath + "\")'/></div>";
	Ext.getCmp(position).body.update(images);

};
/**
 * 
 * @param {}
 *            url (123.pdf#6,123dsfrt34we|123.pdf#6,123dsfrt34we)
 * @param {}
 *            position
 * @param {}
 *            width
 * @param {}
 *            height
 */
com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.loadFiles = function(urls,
		position, width, height) {
	var urlsArray = urls.split("|");
	var fileElement = "";
	for (var i = 0; i < urlsArray.length; i++) {
		var file = urlsArray[i].split("#");
		var filePath = file.pop();
		var fileName = file.shift();
		if (fileName && fileName.substr(fileName.lastIndexOf('.')).toLowerCase() == '.pdf') {
			fileElement += "<div style='padding-left:10%;float:left;'><a target='_blank' style='text-decoration:none;width:"
					+ width
					+ ";height:"
					+ height
					+ "' href=fileServer.do?method=getfile&filepath="
					+ filePath
					+ "&fileName="
					+ fileName
					+ ">"
					+ "<div><image style='width:110px;height:110px;' src='com/jsjn/jnf/withhold/sign/add/form/PDF.jpg' /></div>"
					+ "<div>"
					+ fileName
					+ "</div></a></div>";
		} else {
			fileElement += "<div style='padding-left:10%;float:left;'><img style='width:60%;height:80%';"
					+ " src=fileServer.do?method=getfile&filepath="
					+ filePath
					+ " onclick='com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.showImage(\""
					+ filePath + "\")'/></div>";
		}

	}
	Ext.getCmp(position).body.update(fileElement);

};

//com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.loadPdfFile = function(
//		filePath, fileName, position, width, height) {
//	var pdf = "<div style=\"padding-left:40%\"><a target='_blank' style=\"width:"
//			+ width
//			+ ";height:"
//			+ height
//			+ "\" href=fileServer.do?method=getfile&filepath="
//			+ filePath
//			+ "&fileName=" + fileName + ">" + fileName + "</a></div>";
//	Ext.getCmp(position).body.update(pdf);
//
//};

com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.showImage = function(filePath) {
	var showImageWin = new Ext.Window({
				title : '查看原图',
				width : 600,
				height : 400,
				modal : true,
				closeAction : 'close',
				autoScroll : true,
				html : "<img id='displayImage' src="
						+ "fileServer.do?method=getfile&filepath=" + filePath + "></img>"
			});
	showImageWin.show();
};