/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.withhold.sign.query.WithHoldResign's method: Javascript class
 * static method be used as ExtJs's event method handler,like
 * 'com.jsjn.jnf.withhold.sign.query.WithHoldResign.method(); this is Class
 * static method' Javasctipt object method be used as get or set object's
 * properties,like
 * 'com.jsjn.jnf.withhold.sign.query.WithHoldResign.prototype.method(); this is
 * object's method' com.jsjn.jnf.withhold.sign.query.WithHoldResign.main method
 * is the beginning of all.
 * com.jsjn.jnf.withhold.sign.query.WithHoldResign.WINDOW
 * iscom.jsjn.jnf.withhold.sign.query.WithHoldResign's Singleton instance object .
 * you can get com.jsjn.jnf.withhold.sign.query.WithHoldResign.WINDOW reference
 * by appfram.getInstance('com.jsjn.jnf.withhold.sign.query.WithHoldResign').
 */
appframe.afterInstance("com.jsjn.jnf.withhold.sign.query.WithHoldResign",
		function() {
			com.jsjn.jnf.withhold.sign.query.WithHoldResign.loadComponent();
			com.jsjn.jnf.withhold.sign.query.WithHoldResign.winInit();
		});
com.jsjn.jnf.withhold.sign.query.WithHoldResign.loadComponent = function() {
	Ext.getCmp('front.WithHoldResign').on('afterrender', function(thisPanel) {
				if (thisPanel) {
					uploader = com.jsjn.uploader.initWebUpload(thisPanel.id, {
								fileNumLimit : 1,
								btnName : '选择身份证正面',
								sign : 'front',
								type : 'update'
							});
				}
			});

	Ext.getCmp('back.WithHoldResign').on('afterrender', function(thisPanel) {
				if (thisPanel) {
					com.jsjn.uploader.initWebUpload(thisPanel.id, {
								fileNumLimit : 1,
								btnName : '选择身份证反面',
								sign : 'back',
								type : 'update'
							});
				}
			});

	Ext.getCmp('other.WithHoldResign').on('afterrender', function(thisPanel) {
				if (thisPanel) {
					com.jsjn.uploader.initWebUpload(thisPanel.id, {
								fileNumLimit : 5,
								btnName : '选择支付代扣协议附件',
								sign : 'other',
								type : 'update',
			                    extensions :'jpg,jpeg,bmp,png,pdf',
								mimeTypes:'image/*,application/pdf'
							});
				}
			});
};
com.jsjn.jnf.withhold.sign.query.WithHoldResign.winInit = function() {
	Ext.apply(Ext.getCmp('payStartDay.WithHoldResign'), {
				store : withholdStartDayStore.getStore()
			});
	Ext.getCmp('isBatchPay.WithHoldResign').on('check', function() {
		if (Ext.getCmp('isBatchPay.WithHoldResign').checked) {
			Ext.getCmp('payStartDay.WithHoldResign').disabled = false;
			Ext
					.getCmp("payStartDay.WithHoldResign")
					.setValue(com.jsjn.jnf.withhold.sign.query.WithHoldResign.payStartDay);
			if (Ext.getCmp('recourse.WithHoldResign').getValue() == 'Y') {
				Ext.getCmp('batchTip.WithHoldResign').show();
			} else {
				Ext.getCmp('batchTip.WithHoldResign').hide();
			}
		} else {
			Ext.getCmp('batchTip.WithHoldResign').hide();
			Ext.getCmp('payStartDay.WithHoldResign').setValue('');
			Ext.getCmp('payStartDay.WithHoldResign').disabled = true;
		}

	});
	Ext.getCmp('batchTip.WithHoldResign').hide();
	com.jsjn.jnf.withhold.sign.query.WithHoldResign.payStartDay = "";
	com.jsjn.jnf.withhold.sign.query.WithHoldResign.querySignTempInfoById();
};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.delComp = function() {
	$(".cancel").click();
};
com.jsjn.jnf.withhold.sign.query.WithHoldResign.flowId = "";
com.jsjn.jnf.withhold.sign.query.WithHoldResign.loanNo = "";
com.jsjn.jnf.withhold.sign.query.WithHoldResign.channel = "";
com.jsjn.jnf.withhold.sign.query.WithHoldResign.insttuId = "";
com.jsjn.jnf.withhold.sign.query.WithHoldResign.payStartDay = "";
com.jsjn.jnf.withhold.sign.query.WithHoldResign.querySignTempInfoById = function() {
	// ajax查询贷款信息
	$.ajax({
		url : 'jnf/withhold.do?method=querySignTempInfoById',// 跳转到 action
		data : {
			signRecordId : appConfig.Param.signRecordId
		},
		type : 'post',
		cache : false,
		dataType : 'json',
		success : function(data) {
			if (data.success == true) {
				com.jsjn.jnf.withhold.sign.query.WithHoldResign.flowId = data.data.flowId;
				com.jsjn.jnf.withhold.sign.query.WithHoldResign.loanNo = data.data.loanNo;
				com.jsjn.jnf.withhold.sign.query.WithHoldResign.channel = data.data.channel;
				com.jsjn.jnf.withhold.sign.query.WithHoldResign.insttuId = data.data.insttuId;
				Ext.getCmp('contNo.WithHoldResign').setValue(data.data.contNo);
				Ext.getCmp('custName.WithHoldResign')
						.setValue(data.data.custName);
				Ext.getCmp('idNo.WithHoldResign').setValue(data.data.idNo);
				Ext.getCmp('cardNo.WithHoldResign').setValue(data.data.cardNo);
				Ext.getCmp('mobile.WithHoldResign').setValue(data.data.mobile);
				Ext.getCmp("loanNo.WithHoldResign").setValue(data.data.loanNo);
				Ext.getCmp("repayType.WithHoldResign")
						.setValue(data.data.repayType);
				Ext.getCmp("osPrcp.WithHoldResign").setValue(data.data.osPrcp);
				var isBatchPay = data.data.isBatchPay == 'Y' ? '是' : '否';
				Ext.getCmp('isBatchPay.WithHoldResign').setValue(isBatchPay);
				com.jsjn.jnf.withhold.sign.query.WithHoldResign.payStartDay = data.data.payStartDay;
				Ext.getCmp('payStartDay.WithHoldResign')
						.setValue(data.data.payStartDay);
				var channel  = data.data.channel ;
//				new Ext.util.DelayedTask(function(){
//                	Ext.getCmp('channel.WithHoldResign').setValue(data.data.channel);
//				}).delay(100);
				// 回显示图片信息--身份证信息
				var array = data.data.idFiles.split("|");
				var front = array[0];
				var back = array[1];
				com.jsjn.jnf.withhold.sign.query.WithHoldResign
						.loadImages(front, "frontImg.WithHoldResign", '60%',
								'80%', 'front');
				com.jsjn.jnf.withhold.sign.query.WithHoldResign.loadImages(
						back, "backImg.WithHoldResign", '60%','80%', 'back');
				com.jsjn.jnf.withhold.sign.query.WithHoldResign.loadImages(
						data.data.signFiles, 'otherImg.WithHoldResign',  '60%','80%','other');
				// 查询卡bin
				if (data.data.cardNo != '' || data.data.cardNo != null) {
					// ajax请求
					$.ajax({
						url : 'jnf/withhold.do?method=cardInfoQuery',// 跳转到
																		// action
						data : {
							cardNo : data.data.cardNo
						},
						type : 'post',
						cache : false,
						dataType : 'json',
						success : function(data) {
							if (data.resCode == "000000") {
								// 查询成功
								var kind = data.cardKind == '0' ? "借记卡" : "信用卡";
								// $("#bankName").val(data.bankName+" | "+kind);
								Ext.getCmp('bankName.WithHoldResign')
										.setValue(data.bankName + " | " + kind);

							}
							Ext.getCmp('channel.WithHoldResign').setValue(channel);
						},
						error : function() {
							Ext.Msg.alert('系统提示', data.resMsg);
						}
					});
				}
				
			} else {
				Ext.Msg.alert('系统提示', '查询出错！');
			}
		},
		error : function() {
			Ext.Msg.alert('系统提示', data.resMsg);
		}
	});
};

// 卡bin查询
com.jsjn.jnf.withhold.sign.query.WithHoldResign.queryCardBin = function() {
	var cardNo = Ext.getCmp("cardNo.WithHoldResign").getValue();
	Ext.getCmp("bankName.WithHoldResign").setValue('');
	if (cardNo == "" || cardNo == null) {
		return;
	}

	$.ajax({
				url : 'jnf/withhold.do?method=cardInfoQuery', // 跳转到
				// action
				data : {
					cardNo : cardNo
				},
				type : 'post',
				cache : false,
				dataType : 'json',
				success : function(data) {
					if (data.resCode == "000000") {
						// 查询成功
						var kind = data.cardKind == '0' ? "借记卡" : "信用卡";
						Ext.getCmp("bankName.WithHoldResign")
								.setValue(data.bankName + " | " + kind);

						// 只支持借记卡
						if (data.cardKind != '0') {
							Ext.Msg.alert('系统提示', '暂不支持信用卡！');
							return;
						}

					} else {
						Ext.Msg.alert('系统提示', '输入的银行卡号不正确！');
					}
				},
				error : function() {
					Ext.Msg.alert('系统提示', data.resMsg);
				}
			});

};

// 提交
com.jsjn.jnf.withhold.sign.query.WithHoldResign.submitForm = function() {
	if (Ext.getCmp('contNo.WithHoldResign').getValue() == ""
			|| Ext.getCmp('contNo.WithHoldResign').getValue() == null) {
		Ext.Msg.alert('系统提示', '合同号不能为空！');
		return;
	}
	if (Ext.getCmp('channel.WithHoldResign').getValue() == ""
			|| Ext.getCmp('channel.WithHoldResign').getValue() == null) {
		Ext.Msg.alert('系统提示', '请选择相应渠道！');
		return;
	}
	if (!checkForm('form.WithHoldResign')) {
		return;
	}
	if (Ext.getCmp('bankName.WithHoldResign').getValue().indexOf("信用卡") > 0) {
		Ext.Msg.alert('系统提示', '暂不支持使用信用卡！');
		return;
	}
	var front_img = "";
	if ($(".frontimage").find("img").length > 0) {
		front_img = $(".frontimage").find("img").attr('name');
	} else {
		front_img = $(Ext.getCmp('front.WithHoldResign').body.dom).find('img')
				.attr('name');
	}
	var back_img = "";
	if ($(".backimage").find("img").length > 0) {
		back_img = $(".backimage").find("img").attr('name');
	} else {
		back_img = $(Ext.getCmp('back.WithHoldResign').body.dom).find('img')
				.attr('name');
	}
	var other_obj = "";
	if ($(".otherimage").find("a,img").length > 0) {
		other_obj = $(".otherimage").find("a,img");
	} else {
		other_obj = $(Ext.getCmp('other.WithHoldResign').body.dom).find('a,img');
	}
	var other_img = "";
	if (other_obj.length > 1) {
		other_img = other_obj[0].name;
		for (var i = 1; i < other_obj.length; i++) {
			other_img += "|" + other_obj[i].name;
		}
	} else {
		other_img = other_obj.attr('name');
	}

	var payStartDay = Ext.getCmp('payStartDay.WithHoldResign').getValue();
	var isBatchPay = null;
	if (Ext.getCmp('isBatchPay.WithHoldResign').checked) {
		isBatchPay = 'Y';
	} else {
		isBatchPay = 'N';
	}
	var channel = com.jsjn.jnf.withhold.sign.query.WithHoldResign
			.channelTrans(Ext.getCmp("channel.WithHoldResign").getValue());
			
	var bankName = Ext.getCmp('bankName.WithHoldResign').getValue().split('|').shift();
	var params = {
		contNo : Ext.getCmp("contNo.WithHoldResign").getValue(),
		channel : channel,
		custName : Ext.getCmp("custName.WithHoldResign").getValue(),
		idNo : Ext.getCmp("idNo.WithHoldResign").getValue(),
		cardNo : Ext.getCmp("cardNo.WithHoldResign").getValue(),
		mobile : Ext.getCmp("mobile.WithHoldResign").getValue(),
		repayType : Ext.getCmp("repayType.WithHoldResign").getValue(),
		osPrcp : Ext.getCmp("osPrcp.WithHoldResign").getValue(),
		loanNo : Ext.getCmp("loanNo.WithHoldResign").getValue(),
		state : '1',
		idType : "0",
		payStartDay : payStartDay,
		isBatchPay : isBatchPay,
		mid : appConfig.Param.mid,
		signFiles : other_img,
		idFiles : front_img + "|" + back_img,
		bankName:bankName
	};

	// ajaxLoad('jnf/workflow.do?method=goApprove',params,function(response){
	// var respData = Ext.decode(response.responseText);
	// if(respData.data!=null&&respData.data!=""){
	// if (respData.data.rspCode == '000000') {
	// Ext.Msg.alert('系统提示', '保存成功！',function(){
	// Ext.getCmp('window.WithHoldResign').hide();
	// Ext.getCmp('batchTip.WithHoldResign').hide();
	// });
	// } else {
	// Ext.Msg.alert('系统提示',data.data.rspMsg);
	// }
	// }
	// });

	Ext.Ajax.request({
				url : appConfig.baseUrl + "/jnf/workflow.do?method=goApprove",
				params : params,
				success : function(res) {
					var respData = Ext.decode(res.responseText);
					if (respData && respData.success) {
						Ext.Msg.alert('系统提示', '保存成功！', function() {
									Ext.getCmp('window.WithHoldResign').hide();
									Ext.getCmp('batchTip.WithHoldResign')
											.hide();
								});
					} else {
						Ext.Msg.alert('系统提示', respData.errMsg);
					}
				}
			});
};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.showFee = function(value,
		cellmeta, record, rowIndex, columnIndex, store) {
	var store788408129 = new Ext.data.Store({
				reader : new Ext.data.JsonReader({}, [{
									name : "channelId",
									mapping : "channelId",
									type : "string"
								}, {
									name : "bankName",
									mapping : "bankName",
									type : "string"
								}, {
									name : "jnBankCode",
									mapping : "jnBankCode",
									type : "string"
								}, {
									name : "channelBankCode",
									mapping : "channelBankCode",
									type : "string"
								}, {
									name : "maxAmount",
									mapping : "maxAmount",
									type : "string"
								}, {
									name : "maxAmountDay",
									mapping : "maxAmountDay",
									type : "string"
								}]),
				url : appConfig.baseUrl
						+ '/jnf/bankCardInfo.do?method=queryBankList&channelId='
						+ com.jsjn.jnf.withhold.sign.query.WithHoldResign
								.channelTrans(Ext
										.getCmp('channel.WithHoldResign')
										.getValue())
			});
	var gridPanel527979096 = new Ext.grid.GridPanel({
				layoutConfig : {},
				store : store788408129,
				autoScroll : false,
				columns : [{
					hidden : false,
					width : 60,
					sortable : true,
					align : "center",
					dataIndex : "cplsh",
					renderer : function(value, cellmeta, record, rowIndex,
							columnIndex, store) {
						return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
								.gridRender(value, cellmeta, record, rowIndex,
										columnIndex, store);
					},
					header : "序号"
				}, {
					hidden : false,
					width : 80,
					sortable : true,
					align : "center",
					dataIndex : "channelId",
					renderer : function(value, cellmeta, record, rowIndex,
							columnIndex, store) {
						return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
								.gridRender(value, cellmeta, record, rowIndex,
										columnIndex, store);
					},
					header : "渠道"
				}, {
					hidden : false,
					width : 100,
					sortable : true,
					align : "center",
					dataIndex : "bankName",
					header : "银行名称"
				}, {
					hidden : false,
					width : 120,
					sortable : true,
					align : "right",
					dataIndex : "maxAmount",
					renderer : function(value, cellmeta, record, rowIndex,
							columnIndex, store) {
						return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
								.gridRender(value, cellmeta, record, rowIndex,
										columnIndex, store);
					},
					header : "	单笔额度(元)"
				}, {
					hidden : false,
					width : 120,
					sortable : true,
					align : "right",
					dataIndex : "maxAmountDay",
					renderer : function(value, cellmeta, record, rowIndex,
							columnIndex, store) {
						return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
								.gridRender(value, cellmeta, record, rowIndex,
										columnIndex, store);
					},
					header : "	单日额度(元)"
				}, {
					hidden : false,
					width : 80,
					sortable : true,
					align : "right",
					dataIndex : "fee",
					renderer : function(value, cellmeta, record, rowIndex,
							columnIndex, store) {
						return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
								.gridRender(value, cellmeta, record, rowIndex,
										columnIndex, store);
					},
					header : "费用(元)"
				}],
				autoWidth : false,
				autoHeight : false,
				id : "grid.QryFeeInfoList",
				height : 380,
				columnWidth : "1",
				selModel : new Ext.grid.RowSelectionModel({
							singleSelect : false
						}),
				viewConfig : {},
				loadMask : {
					msg : "正在载入数据...",
					title : "提示"
				}
			});
	store788408129.load();
	var win = new Ext.Window({
				title : '费用查询',
				width : 600,
				closeAction : 'close',
				modal : true,
				items : [gridPanel527979096]
			});
	win.show();
};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.loadImages = function(urls,
		position, width, height, sign) {
			
	
//	var urlsArray = urls.split("|");
//	var fileElement = "";
//	for (var i = 0; i < urlsArray.length; i++) {
//		var file = urlsArray[i].split("#");
//		var filePath = file.pop();
//		var fileName = file.shift();
//		if (fileName && fileName.substr(fileName.lastIndexOf('.')).toLowerCase() == '.pdf') {
//			fileElement += "<div style=\"padding-left:40%\"><a target='_blank' style=\"width:"
//					+ width
//					+ ";height:"
//					+ height
//					+ "\" href=fileServer.do?method=getfile&filepath="
//					+ filePath
//					+ "&fileName="
//					+ fileName
//					+ ">"
//					+ fileName
//					+ "</a></div>";
//		} else {
//			fileElement += "<div style=\"padding-left:40%\"><image style=\"width:"
//					+ width
//					+ ";height:"
//					+ height
//					+ "\" src=fileServer.do?method=getfile&filepath="
//					+ filePath
//					+ " onclick='com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.showImage(\""
//					+ filePath + "\")'/></div>";
//		}
//
//	}
//	Ext.getCmp(position).body.update(fileElement);
			
	
	var urlsArray = urls.split("|");
	var images = "<div class='"+sign+"image' align=center style='padding-left:10%;float:left;'>";
	for (var i = 0; i < urlsArray.length; i++) {
		var file = urlsArray[i].split("#");
		var filePath = file.pop();
		var fileName = file.shift();
		
		if (fileName && fileName.substr(fileName.lastIndexOf('.')).toLowerCase() == '.pdf') {
			images += "<a target='_blank' style='text-decoration:none;width:"
					+ width
					+ ";height:"
					+ height
					+ "' href=fileServer.do?method=getfile&filepath="
					+ filePath
					+ "&fileName="
					+ fileName
					+ ">"
					+ "<div><image  src='com/jsjn/jnf/withhold/sign/add/form/PDF.jpg' /></div>"
					+ "<div>"
					+ fileName
					+ "</div></a>";
		} else {
			images += "<image style='width:60%;height:80%' src=fileServer.do?method=getfile&filepath="
					+ filePath
					+ " onclick='com.jsjn.jnf.withhold.sign.query.WithHoldResign.showImage(\""
					+ filePath + "\")'/>";
		}
		
		
//		if (fileName && fileName.substr(fileName.lastIndexOf('.')).toLowerCase() == '.pdf') {
//			images += "<a target='_blank' style=\"width:"
//					+ width
//					+ ";height:"
//					+ height
//					+ "\" href=fileServer.do?method=getfile&filepath="
//					+ filePath
//					+ "&fileName="
//					+ fileName
//					+" name="+ urlsArray[i]
//					+ ">"
//					+ fileName
//					+ "</a>";
//		} else {
//		
//			images += "<image style=\"width:"
//					+ width
//					+ ";height:"+ height + "\" src=fileServer.do?method=getfile&filepath="+ filePath
//					+" name="+ urlsArray[i]
//					+ " onclick='com.jsjn.jnf.withhold.sign.query.WithHoldResign.showImage(\""
//					+ filePath + "\")'/>";
//		}
		
		
	}
	images += "</div>";
	Ext.getCmp(position).body.update(images);

};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.winClose = function() {
	$(".cancel").click();
	com.jsjn.jnf.withhold.sign.query.WithHoldResign.winInit();
};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.channelTrans = function(value) {
	var data = Ext.getCmp("channel.WithHoldResign").store.reader.jsonData;
	var reVal = value;
	$.each(data, function(k, v) {
				if (v.channelName == value) {
					reVal = v.channelId;
				}
			});
	return reVal;
};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.showChannel = function(key) {
	$.ajax({
				url : "jnf/withhold.do?method=findAllMenuByCode",
				data : {
					menuCde : 'WITHHOLD_CHANNEL'
				},
				type : "post",
				datatype : "json",
				async : false,
				success : function(data) {
					var rsp = eval('(' + data + ')');
					if (rsp) {
						var array = rsp.root;
						for (var i = 0; i < array.length; i++) {
							if (key == array[i].menuKey) {
								Ext.getCmp('channel.WithHoldResign')
										.setValue(array[i].menuValue);
								return;
							}
						}
					}

				}
			});
};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.chkMobile = function(form) {
	var mobile  = Ext.getCmp('mobile.WithHoldResign').getValue();
	if (!(/^1[34578]\d{9}$/.test(mobile))) {
		Ext.Msg.alert('系统提示', '输入的手机号不正确！');
	}
};

com.jsjn.jnf.withhold.sign.query.WithHoldResign.showImage = function(filePath) {
	var showImageWin = new Ext.Window({
				title : '查看原图',
				width : 600,
				height : 400,
				modal : true,
				closeAction : 'close',
				autoScroll : true,
				html : "<img id='displayImage' src="
						+ "fileServer.do?method=getfile&filepath=" + filePath + "></img>"
			});
	showImageWin.show();
};
