/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.trade.QryTradeListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.trade.QryTradeListMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.trade.QryTradeListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.trade.QryTradeListMgr.PANEL is com.jsjn.jnf.trade.QryTradeListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.trade.QryTradeListMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.trade.QryTradeListMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.trade.QryTradeListMgr",function() {
		girdStoreAddExceptionEvent('grid.QryTradeListMgr',
		"com.jsjn.jnf.trade.QryTradeListMgr");
		
		//渲染下拉框
		Ext.apply(Ext.getCmp('tradeType.QryTradeListMgr'), {
			store : tradeTypeStore.getStore()
		});	
		Ext.apply(Ext.getCmp('status.QryTradeListMgr'), {
			store : tradeStatusStore.getStore()
		});	
		
		Ext.getCmp('grid.QryTradeListMgr').getView().getRowClass=function(record,rowIndex,rowParams,store){
		    var valid = record.json.valid;
		    
			if(valid == false){
				return 'x-grid-record-red';
			};
		};
		
});

com.jsjn.jnf.trade.QryTradeListMgr.addParams = function() {
	var tradeNo = Ext.getCmp('tradeNo.QryTradeListMgr').getValue();	//交易订单编号
	var mSerialNo = Ext.getCmp('mSerialNo.QryTradeListMgr').getValue();	//商户订单流水号
	var tradeType = Ext.getCmp('tradeType.QryTradeListMgr').getValue();	//交易类型
	var mid = Ext.getCmp('mid.QryTradeListMgr').getValue();	//商户编号
	var externLoanNo = Ext.getCmp('externLoanNo.QryTradeListMgr').getValue();	//外部合同编号
	var amountMin = Ext.getCmp('amountMin.QryTradeListMgr').getValue(); //支付金额（起）
	var amountMax = Ext.getCmp('amountMax.QryTradeListMgr').getValue(); //支付金额（止）
	var modifiedMin = Ext.getCmp('modifiedMin.QryTradeListMgr').getRawValue(); //支付时间（起）
	var modifiedMax = Ext.getCmp('modifiedMax.QryTradeListMgr').getRawValue(); //支付时间（止）

	
	if( amountMin != '' && amountMax != '' &&  amountMin > amountMax){
		Ext.Msg.alert('系统提示', '交易金额（起）不能大于交易金额（止）');
		return false;
	}
	if( modifiedMin != '' && modifiedMax != '' && modifiedMin > modifiedMax){
		Ext.Msg.alert('系统提示', '交易时间（起）不能大于交易时间（止）');
		return false;
	}
	
	var params = {
			tradeNo : tradeNo,
			mSerialNo : mSerialNo,
			tradeType : tradeType,
			mid : mid,
			externLoanNo : externLoanNo,
			amountMin : amountMin,
			amountMax : amountMax,
			modifiedMin : modifiedMin,
			modifiedMax : modifiedMax
	};
	
	var gStore = Ext.getCmp('grid.QryTradeListMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};


com.jsjn.jnf.trade.QryTradeListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var valid = record.json.valid;//数据是否被篡改
	
	var dataIndex = Ext.getCmp("grid.QryTradeListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'operator') {
		var operater = "";
		if(valid == true){
			operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.trade.QryTradeListMgr.detail();\" style=\"vertical-align:bottom; text-decoration:none\">【详情】</a>";
		}else{
			operater += "警告：数据被篡改";
		}
		return operater;
	}
	if (dataIndex == 'amount') {
		return formatMoney(value);
	}
	if (dataIndex == 'tradeType') {
		return storeFind(tradeTypeStore, value);
	}
	if (dataIndex == 'status') {
		return storeFind(tradeStatusStore, value);
	}
	if (dataIndex == 'modified') {
		return formatDateToPattern("YYYY-MM-DD",new Date(new Number(value)));
	}
	
	return value;
};

/**
 * 点击查询按钮
 */
com.jsjn.jnf.trade.QryTradeListMgr.btnQuery = function(){

	Ext.getCmp('grid.QryTradeListMgr').getStore().load();
};

/**
 * 点击重置按钮
 */
com.jsjn.jnf.trade.QryTradeListMgr.btnReset = function(){
	Ext.getCmp('form.QryTradeListMgr').getForm().reset();
};

/**
 * 详情按钮
 */
com.jsjn.jnf.trade.QryTradeListMgr.detail = function(){
	var record = Ext.getCmp('grid.QryTradeListMgr').getSelectionModel().getSelected();
	
	var win = appframe.getInstance("com.jsjn.jnf.trade.TradeInfoDetailMgr");
	
	win.show();
	
	com.jsjn.jnf.trade.TradeInfoDetailMgr.panelInit(record);
};
