/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.withhold.sign.add.QryFeeInfoList's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.prototype.method(); this is object's method'
 * com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.main method is the beginning of all.
 * com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.WINDOW  iscom.jsjn.jnf.withhold.sign.add.QryFeeInfoList's  Singleton instance object .
 * you can get com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.withhold.sign.add.QryFeeInfoList'). 
 */
appframe.afterInstance("com.jsjn.jnf.withhold.sign.add.QryFeeInfoList", function(){
	com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.winInit();	
});

com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.winInit=function(){
	Ext.getCmp('grid.QryFeeInfoList').getStore().load();
	girdStoreAddExceptionEvent('grid.QryFeeInfoList',
	"com.jsjn.jnf.withhold.sign.add.QryFeeInfoList");	
};

com.jsjn.jnf.withhold.sign.add.QryFeeInfoList.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var dataIndex = Ext.getCmp("grid.QryFeeInfoList").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'channelId') {
		if(value=="CH11"){
			return "天下支付";
		}
	}
	if (dataIndex == 'channelId') {
		if(value=="CH10"){
			return "苏宁易付宝";
		}
	}
	if (dataIndex == 'channelId') {
		if(value=="CH12"){
			return "金农征信平台";
		}
	}
	if (dataIndex == 'maxAmount') {
		if(value == ""){
			return "不限";
		}else{
			return formatMoney(value);
		}
	}
	if (dataIndex == 'maxAmountDay') {
		if(value == ""){
			return "不限";
		}else{
			return formatMoney(value);
		}
	}
	if (dataIndex == 'fee') {
		return formatMoney("2.00");
	}
	return value;
};



