/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.withhold.sign.add.QryLoanCodeList's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.prototype.method(); this is object's method'
 * com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.main method is the beginning of all.
 * com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.WINDOW  iscom.jsjn.jnf.withhold.sign.add.QryLoanCodeList's  Singleton instance object .
 * you can get com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.withhold.sign.add.QryLoanCodeList'). 
 */

com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.start = 0;//序号初始值
appframe.afterInstance("com.jsjn.jnf.withhold.sign.add.QryLoanCodeList", function(){
	
	girdStoreAddExceptionEvent('grid.QryLoanCodeList',
	"com.jsjn.jnf.withhold.sign.add.QryLoanCodeList");
	
	gridSelectionModelVisible('grid.QryLoanCodeList');
	
	Ext.getCmp('grid.QryLoanCodeList').getBottomToolbar().doLoad = function(start) {
        com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.start = start;
        this.store.load({
            params : {
                'start' : start,
                'limit' : 10
            }
        });
    };
	 
	
	//渲染下拉框 证件类型
	Ext.apply(Ext.getCmp('idType.QryLoanCodeList'), {
		store : withholdCardStateStore.getStore()
	});	
	
	//渲染下拉框 客户类型
	Ext.apply(Ext.getCmp('custType.QryLoanCodeList'), {
		store : withholdCustStateStore.getStore()
	});	
	
});

//页面初始化
com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.winInit = function() {
	com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.reset();
	Ext.getCmp('grid.QryLoanCodeList').getStore().removeAll();
	Ext.getCmp('grid.QryLoanCodeList').getStore().load();
};

com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.addParams = function() {
	var custName = Ext.getCmp('custName.QryLoanCodeList').getValue();	//客户名称
	var custType = Ext.getCmp('custType.QryLoanCodeList').getValue();	//客户类型
	var idType = Ext.getCmp('idType.QryLoanCodeList').getValue(); //证件类型
	var idNo = Ext.getCmp('idNo.QryLoanCodeList').getValue(); //证件号码
	var startTime = Ext.getCmp('startTime.QryLoanCodeList').getRawValue(); //贷款日期（起）
	var endTime = Ext.getCmp('endTime.QryLoanCodeList').getRawValue(); //贷款日期（止）
	var contNo = Ext.getCmp('contNo.QryLoanCodeList').getValue(); //贷款合同号

	if( startTime!="" && endTime !="" && startTime > endTime){
		Ext.Msg.alert('系统提示', '贷款日期（起）不能大于贷款日期（止）');
		return false;
	}
	
	var params = {
			custName : "%" +custName+"%",
			custType : custType,
			paperType : idType,
			paperNo : idNo,
			intStartDtS : startTime,
			intStartDtE : endTime,
			contNoExt : "%"+contNo+"%",
			custManagerNo:appConfig.Session.loginUserInfo.id.userId,
			orgNo:appConfig.Session.loginUserInfo.id.insttuId,
			setlFlg:'N',
	};
	
	var gStore = Ext.getCmp('grid.QryLoanCodeList').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var dataIndex = Ext.getCmp("grid.QryLoanCodeList").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1 + com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.start;
	}
	if (dataIndex == 'custType') {
		return storeFind(withholdCustStateStore, value);
	}
	if (dataIndex == 'idType') {
		return storeFind(withholdCardStateStore, value);
	}
	if (dataIndex == 'repayType') {
		return storeFind(withholdRepayTypeStore, value);
	}
	if (dataIndex == 'osPrcp') {
		return formatMoney(value);
	}
	if (dataIndex == 'resPrcp') {
		return formatMoney(value);
	}
	return value;
};

/**
 * 点击查询按钮
 */
com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.qry = function(){
    Ext.getCmp('grid.QryLoanCodeList').getStore().load();
};
/**
 * 点击重置按钮
 */
com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.reset = function(){
    Ext.getCmp('form.QryLoanCodeList').getForm().reset();
};

/**
 * 确认选择该贷款合同号
 */
com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.confirm = function(){
	
	var record = Ext.getCmp('grid.QryLoanCodeList').getSelectionModel().getSelected();

	com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.WINDOW.hide();
	
	com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.signWithholdForWindow(record);
	
};
