/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.panda.extPage.EditParam's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.panda.extPage.EditParam.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.panda.extPage.EditParam.prototype.method(); this is object's method'
 * com.jsjn.panda.extPage.EditParam.PANEL is com.jsjn.panda.extPage.EditParam's  Singleton instance object .
 * you can get com.jsjn.panda.extPage.EditParam.PANEL's reference  by appfram.getInstance('com.jsjn.panda.extPage.EditParam'). 
 */
