/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.prototype.method(); this is object's method'
 * com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.main method is the beginning of all.
 * com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.WINDOW  iscom.jsjn.jnf.withhold.sign.query.AddWithHoldInfo's  Singleton instance object .
 * you can get com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo').
 */
appframe.afterInstance("com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo", function(panel) {
    if (panel) {
        //zhengm.AddWithholdInfo
        Ext.getCmp('front.AddWithholdInfo').on('afterrender', function(thisPanel) {
            if (thisPanel) {
                uploader = com.jsjn.uploader.initWebUpload(thisPanel.id, {
                    fileNumLimit: 1,
                    btnName: '选择身份证正面',
                    sign:'front',
                    type:'add'
                });
            }
        });

        Ext.getCmp('back.AddWithholdInfo').on('afterrender', function(thisPanel) {
            if (thisPanel) {
                com.jsjn.uploader.initWebUpload(thisPanel.id, {
                    fileNumLimit: 1,
                    btnName: '选择身份证反面',
                    sign:'back',
                    type:'add'
                });
            }
        });

        Ext.getCmp('other.AddWithholdInfo').on('afterrender', function(thisPanel) {
            if (thisPanel) {
                com.jsjn.uploader.initWebUpload(thisPanel.id, {
                    fileNumLimit: 5,
                    btnName: '选择支付代扣协议附件',
                    sign:'other',
                    type:'add',
                    extensions :'jpg,jpeg,bmp,png,pdf',
					mimeTypes:'image/*,application/pdf'
                });
            }
        });
        Ext.getCmp('cardNo.AddWithHoldInfo').on('blur', function() {
            com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.queryCardBin();
        });

        Ext.getCmp('isBatchPay.AddWithHoldInfo').on('check', function() {
        	if(Ext.getCmp('isBatchPay.AddWithHoldInfo').checked){
        		 Ext.getCmp('payStartDay.AddWithHoldInfo').setValue(com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.payStartDay);
        		Ext.getCmp('payStartDay.AddWithHoldInfo').disabled=false;
        		 if (Ext.getCmp('recourse.AddWithHoldInfo').getValue() == 'Y') {
                     Ext.getCmp('batchTip.AddWithHoldInfo').show(); 
                 }else{
                	 Ext.getCmp('batchTip.AddWithHoldInfo').hide();
                 }
        	}else{
        		Ext.getCmp('batchTip.AddWithHoldInfo').hide();
        		Ext.getCmp('payStartDay.AddWithHoldInfo').setValue('');
        		Ext.getCmp('payStartDay.AddWithHoldInfo').disabled=true;
        	}
           
        });
    }
//    Ext.getCmp('queryFeeInfo.AddWithHoldInfo').disabled=true;
    Ext.apply(Ext.getCmp('payStartDay.AddWithHoldInfo'), {
        store: withholdStartDayStore.getStore()
    });

});

//卡bin查询
com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.queryCardBin = function() {
    var cardNo = Ext.getCmp("cardNo.AddWithHoldInfo").getValue();
    Ext.getCmp("bankName.AddWithHoldInfo").setValue('');
    if (cardNo == "" || cardNo == null) {
        return;
    }
    $.ajax({
        url: 'jnf/withhold.do?method=cardInfoQuery', // 跳转到
        // action
        data: {
            cardNo: cardNo
        },
        type: 'post',
        cache: false,
        dataType: 'json',
        success: function(data) {
            if (data.resCode == "000000") {
                // 查询成功
                var kind = data.cardKind == '0' ? "借记卡" : "信用卡";
                Ext.getCmp("bankName.AddWithHoldInfo").setValue(
                    data.bankName + " | " + kind);

                // 只支持借记卡
                if (data.cardKind != '0') {
                    Ext.Msg.alert('系统提示', '暂不支持信用卡！');
                    return;
                }

            } else {
                Ext.Msg.alert('系统提示', '输入的银行卡号不正确！');
            }
        },
        error: function() {
            Ext.Msg.alert('系统提示', data.resMsg);
        }
    });

};

//提交
com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.submitForm = function() {
	if(Ext.getCmp('contNo.AddWithHoldInfo').getValue()==""||Ext.getCmp('contNo.AddWithHoldInfo').getValue()==null){
		  Ext.Msg.alert('系统提示', '合同号不能为空！');
	        return;
	}
	if(Ext.getCmp('channel.AddWithHoldInfo').getValue()==""||Ext.getCmp('channel.AddWithHoldInfo').getValue()==null){
		Ext.Msg.alert('系统提示', '请选择相应渠道！');
        return;
	}
    if (!checkForm('form.AddWithHoldInfo')) {
        return;
    }
    if(Ext.getCmp('bankName.AddWithHoldInfo').getValue().indexOf("信用卡")>0){
    	Ext.Msg.alert('系统提示', '暂不支持使用信用卡！');
    	return;
    }
    
    var front_img = $("div[name='front']").next().find("img").attr("name");
    var back_img = $("div[name='back']").next().find("img").attr("name");
    
    var other_obj = $("div[name='other']").next().find("a,img");
    var other_file = "";
    if (other_obj.length > 1) {
        other_file = other_obj[0].name;
        for (var i = 1; i < other_obj.length; i++) {
            other_file += "|" + other_obj[i].name;
        }
    } else {
        other_file = other_obj.attr('name');
    }

    if (valueIsEmpty(front_img)) {
        Ext.Msg.alert('系统提示', '未上传身份证正面照片！');
        return;
    }
    if (valueIsEmpty(back_img)) {
        Ext.Msg.alert('系统提示', '未上传身份证反面照片！');
        return;
    }
    if (valueIsEmpty(other_file)) {
        Ext.Msg.alert('系统提示', '未上传支付代扣协议附件！');
        return;
    }

    var payStartDay = Ext.getCmp('payStartDay.AddWithHoldInfo').getValue();
    var isBatchPay = null;
    if (Ext.getCmp('isBatchPay.AddWithHoldInfo').checked) {
        isBatchPay = 'Y';
    } else {
        isBatchPay = 'N';
    }
    
	var bankName = Ext.getCmp('bankName.AddWithHoldInfo').getValue().split('|').shift();
    var params={
            contNo: Ext.getCmp("contNo.AddWithHoldInfo").getValue(),
            channel: Ext.getCmp("channel.AddWithHoldInfo").getValue(),
            custName: Ext.getCmp("custName.AddWithHoldInfo").getValue(),
            idNo: Ext.getCmp("idNo.AddWithHoldInfo").getValue(),
            cardNo: Ext.getCmp("cardNo.AddWithHoldInfo").getValue(),
            mobile: Ext.getCmp("mobile.AddWithHoldInfo").getValue(),
            repayType: Ext.getCmp("repayType.AddWithHoldInfo").getValue(),
            osPrcp: Ext.getCmp("osPrcp.AddWithHoldInfo").getValue(),
            loanNo: Ext.getCmp("loanNo.AddWithHoldInfo").getValue(),
            state: '1',
            idType: "0",
            payStartDay: payStartDay,
            isBatchPay: isBatchPay,
            mid: appConfig.Param.mid,
            signFiles: other_file,
            idFiles: front_img + "|" + back_img,
            bankName:bankName
        };
        
        Ext.Ajax.request({
		   url: appConfig.baseUrl + "/jnf/workflow.do?method=goApprove",
		   params: params,
		   success: function(res) {
			   var respData = Ext.decode(res.responseText);
			   if(respData && respData.success){
					Ext.Msg.alert('系统提示', '保存成功！',function(){
						Ext.getCmp('window.AddWithHoldInfo').hide();
						Ext.getCmp('batchTip.AddWithHoldInfo').hide();
					});
		    	}else {
					Ext.Msg.alert('系统提示',respData.errMsg);
		    	}
		   }
		});
        
//    ajaxLoad('jnf/workflow.do?method=goApprove',params,function(response){
//    	var respData = Ext.decode(response.responseText);
//    	console.log(respData);
//    	if(respData && respData.success){
//			Ext.Msg.alert('系统提示', '保存成功！',function(){
//				Ext.getCmp('window.AddWithHoldInfo').hide();
//				Ext.getCmp('batchTip.AddWithHoldInfo').hide();
//			});
//    	}else {
//			Ext.Msg.alert('系统提示',respData.errMsg);
//    	}
//    });
};


/**
 * 添加查询贷款合同号方法
 * 
 */
com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.qryLoanNo = function() {

	var win = appframe
			.getInstance("com.jsjn.jnf.withhold.sign.add.QryLoanCodeList");
	com.jsjn.jnf.withhold.sign.add.QryLoanCodeList.winInit();
	if (win) {
		Ext.getCmp('form.QryLoanCodeList').getForm().reset();
		Ext.getCmp("custType.QryLoanCodeList").setValue('0');
		Ext.getCmp("idType.QryLoanCodeList").setValue('0');
	}
	win.show();
};

/**
 * 费用说明
 */
com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.qryFeeInfo= function() {
	appConfig.Param.channelId=Ext.getCmp('channel.AddWithHoldInfo').getValue();
	var win = appframe.getInstance("com.jsjn.jnf.withhold.sign.add.QryFeeInfoList");
    win.show();
};
/**
 * 改变按钮
 */
com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.changeButton=function(){
	Ext.getCmp('queryFeeInfo.AddWithHoldInfo').disabled=false;
};

com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.pageInit=function(){
	Ext.getCmp('contNo.AddWithHoldInfo').setValue('');
	Ext.getCmp('channel.AddWithHoldInfo').setValue('');
	Ext.getCmp('custName.AddWithHoldInfo').setValue('');
	Ext.getCmp('idNo.AddWithHoldInfo').setValue('');
	Ext.getCmp('cardNo.AddWithHoldInfo').setValue('');
	Ext.getCmp('bankName.AddWithHoldInfo').setValue('');
	Ext.getCmp('mobile.AddWithHoldInfo').setValue('');
	Ext.getCmp('repayType.AddWithHoldInfo').setValue('');
	Ext.getCmp('osPrcp.AddWithHoldInfo').setValue('');
	Ext.getCmp('loanNo.AddWithHoldInfo').setValue('');
	Ext.getCmp('recourse.AddWithHoldInfo').setValue('');
	Ext.getCmp('payStartDay.AddWithHoldInfo').setValue('');
	Ext.getCmp('batchTip.AddWithHoldInfo').hidden=true;
	$(".cancel").click();	
};

com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.showFee=function(value, cellmeta,
		record, rowIndex, columnIndex, store){
	var store788408129 = new Ext.data.Store({
		reader : new Ext.data.JsonReader({}, [{
			name : "channelId",
			mapping : "channelId",
			type : "string"
		}, {
			name : "bankName",
			mapping : "bankName",
			type : "string"
		}, {
			name : "jnBankCode",
			mapping : "jnBankCode",
			type : "string"
		}, {
			name : "channelBankCode",
			mapping : "channelBankCode",
			type : "string"
		}, {
			name : "maxAmount",
			mapping : "maxAmount",
			type : "string"
		}, {
			name : "maxAmountDay",
			mapping : "maxAmountDay",
			type : "string"
		}]),
		url : appConfig.baseUrl
				+ '/jnf/bankCardInfo.do?method=queryBankList&channelId='
				+ Ext.getCmp("channel.AddWithHoldInfo").getValue()
	});

	var gridPanel527979096 = new Ext.grid.GridPanel({
		layoutConfig : {},
		store : store788408129,
		autoScroll : false,
		columns : [{
			hidden : false,
			width : 60,
			sortable : true,
			align : "center",
			dataIndex : "cplsh",
			renderer : function(value, cellmeta, record, rowIndex,
					columnIndex, store) {
				return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
						.gridRender(value, cellmeta, record, rowIndex,
								columnIndex, store);
			},
			header : "序号"
		}, {
			hidden : false,
			width : 80,
			sortable : true,
			align : "center",
			dataIndex : "channelId",
			renderer : function(value, cellmeta, record, rowIndex,
					columnIndex, store) {
				return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
						.gridRender(value, cellmeta, record, rowIndex,
								columnIndex, store);
			},
			header : "渠道"
		}, {
			hidden : false,
			width : 100,
			sortable : true,
			align : "center",
			dataIndex : "bankName",
			header : "银行名称"
		}, {
			hidden : false,
			width : 120,
			sortable : true,
			align : "right",
			dataIndex : "maxAmount",
			renderer : function(value, cellmeta, record, rowIndex,
					columnIndex, store) {
				return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
						.gridRender(value, cellmeta, record, rowIndex,
								columnIndex, store);
			},
			header : "	单笔额度(元)"
		}, {
			hidden : false,
			width : 120,
			sortable : true,
			align : "right",
			dataIndex : "maxAmountDay",
			renderer : function(value, cellmeta, record, rowIndex,
					columnIndex, store) {
				return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
						.gridRender(value, cellmeta, record, rowIndex,
								columnIndex, store);
			},
			header : "	单日额度(元)"
		}, {
			hidden : false,
			width : 80,
			sortable : true,
			align : "right",
			dataIndex : "fee",
			renderer : function(value, cellmeta, record, rowIndex,
					columnIndex, store) {
				return com.jsjn.jnf.withhold.sign.add.QryFeeInfoList
						.gridRender(value, cellmeta, record, rowIndex,
								columnIndex, store);
			},
			header : "费用(元)"
		}],
		autoWidth : false,
		autoHeight : false,
		id : "grid.QryFeeInfoList",
		height : 380,
		columnWidth : "1",
		selModel : new Ext.grid.RowSelectionModel({
			singleSelect : false
		}),
		viewConfig : {},
		loadMask : {
			msg : "正在载入数据...",
			title : "提示"
		}
	});
	store788408129.load();
	var win = new Ext.Window({
        title : '费用查询',
        width : 600,
        closeAction : 'close',
        modal:true,
        items : [gridPanel527979096]
	});
	win.show();
};

com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.chkMobile = function(form) {
	var mobile =  Ext.getCmp('mobile.AddWithHoldInfo').getValue();
	if (!(/^1[34578]\d{9}$/.test(mobile))) {
		 Ext.Msg.alert('系统提示', '输入的手机号不正确！');
	}		
};
com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.payStartDay="";
com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.signWithholdForWindow=function(record){
	var contNo = record.data.contNo;
	var custName = record.data.custName;
	var idNo = record.data.idNo;
	var repayType = record.data.repayType;
	var osPrcp = record.data.osPrcp;
	var loanNo = record.data.loanNo;
	var payStartDay=record.json.payStartDay;
	com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.payStartDay=payStartDay;
	var recourse=record.json.recourse;
	Ext.getCmp("contNo.AddWithHoldInfo").setValue(contNo);
	Ext.getCmp("custName.AddWithHoldInfo").setValue(custName);
	Ext.getCmp("idNo.AddWithHoldInfo").setValue(idNo);
	Ext.getCmp("repayType.AddWithHoldInfo").setValue(repayType);
	Ext.getCmp("osPrcp.AddWithHoldInfo").setValue(osPrcp);
	Ext.getCmp("loanNo.AddWithHoldInfo").setValue(loanNo);
	Ext.getCmp("payStartDay.AddWithHoldInfo").setValue(payStartDay);
	Ext.getCmp("recourse.AddWithHoldInfo").setValue(recourse);
	if(recourse=='Y'){
		 Ext.getCmp('batchTip.AddWithHoldInfo').show();
	}
};

com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.btnDis=function(){
	Ext.getCmp('batchTip.AddWithHoldInfo').hide();
	Ext.getCmp('queryFeeInfo.AddWithHoldInfo').disabled=true;
	com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.payStartDay="";
};
