/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.prototype.method(); this is object's method'
 * com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.PANEL is com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo's  Singleton instance object .
 * you can get com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo'). 
 */
appframe.afterInstance("com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo", function(){
//	var imageUrls=signFiles.split('|');
//	var imageInfo="";
//	for(var i=0;i<imageUrls.length;i++){
//		imageInfo+="<div style='padding:20px 0px'><img src='com/jsjn/jnf/withhold/sign/add/form/demo_front.jpg'  alt='示例图片' style='width: 90%; height: 150px'></img></div>";
//	}
//	$(Ext.getCmp('other.ApproveWithHoldInfo')).find("#otherImage").html(imageInfo);
	com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.querySignTempInfoById();
});

com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.flowId="";
com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loanNo="";
com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.channel="";
com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.insttuId="";
com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.querySignTempInfoById = function(){
	//ajax查询贷款信息
	$.ajax( {  
		url:'jnf/withhold.do?method=querySignTempInfoById',// 跳转到 action  
		data:{  
			signRecordId : appConfig.Param.tempParam.split("|")[0],  
		},  
		type:'post',  
		cache:false,  
		dataType:'json',  
		success:function(data) {
			if(data.success==true){				
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.flowId=data.data.flowId;
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loanNo = data.data.loanNo;
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.channel = data.data.channel;
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.insttuId = data.data.insttuId;
				//回显信息
//				$('#contNo').val(data.data.contNo);
//				$('#custName').val(data.data.custName);
//				$('#idNo').val(data.data.idNo);
//				$('#cardNo').val(data.data.cardNo);
//				$('#mobile').val(data.data.mobile);
				Ext.getCmp('contNo.ApproveWithHoldInfo').setValue(data.data.contNo);
				Ext.getCmp('custName.ApproveWithHoldInfo').setValue(data.data.custName);
				Ext.getCmp('idNo.ApproveWithHoldInfo').setValue(data.data.idNo);
				Ext.getCmp('cardNo.ApproveWithHoldInfo').setValue(data.data.cardNo);
				Ext.getCmp('mobile.ApproveWithHoldInfo').setValue(data.data.mobile);
				var isBatchPay=data.data.isBatchPay=='Y'?'是':'否';
				Ext.getCmp('isBatchPay.ApproveWithHoldInfo').setValue(isBatchPay);
				Ext.getCmp('payStartDay.ApproveWithHoldInfo').setValue(data.data.payStartDay);
				//回显渠道中文
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.showChannel(data.data.channel);
				
				//回显示图片信息--身份证信息
				var array = data.data.idFiles.split("|");
				var front = array[0];
				var back = array[1];
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loadImage(front,"front.ApproveWithHoldInfo",'60%','80%');
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loadImage(back,"back.ApproveWithHoldInfo",'60%','80%');
				com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loadImages(data.data.signFiles,'other.ApproveWithHoldInfo','60%','80%');
				
				//查询卡bin
				if(data.data.cardNo!='' || data.data.cardNo!=null){
					//ajax请求
					$.ajax({  
						url:'jnf/withhold.do?method=cardInfoQuery',// 跳转到 action  
						data:{  
							cardNo : data.data.cardNo,  
						},  
						type:'post',  
						cache:false,  
						dataType:'json',  
						success:function(data) {  
							if(data.resCode=="000000"){  
								//查询成功  
								var kind = data.cardKind=='0'?"借记卡":"信用卡";
//								$("#bankName").val(data.bankName+" | "+kind);
								Ext.getCmp('bankName.ApproveWithHoldInfo').setValue(data.bankName+" | "+kind);
								
							}},  
							error : function() {  
								Ext.Msg.alert('系统提示', data.resMsg);
							}  
					});
				}
				
			}else{
				Ext.Msg.alert('系统提示', '查询出错！');
			}
		},  
		error : function() {  
			Ext.Msg.alert('系统提示', data.resMsg);
		}  
	});
};

com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.showChannel = function(key){
	$.ajax({ 
		url:"jnf/withhold.do?method=findAllMenuByCode", 
		data:{menuCde:'WITHHOLD_CHANNEL'},
		type:"post", 
		datatype:"json", 
		async: false,
		success:function(data){ 
			var rsp = eval('('+data+')');
			if(rsp){ 
				var array = rsp.root;
				for(var i=0;i<array.length;i++){
					if(key == array[i].menuKey){
						Ext.getCmp('channel.ApproveWithHoldInfo').setValue(array[i].menuValue);
						return;
					}
				}
			}
			        
		} 
	}); 
};

com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loadImages = function(
		urls, position,width,height) {
	var urlsArray = urls.split("|");
	var fileElement = "";
	for (var i = 0; i < urlsArray.length; i++) {
		var file = urlsArray[i].split("#");
		var filePath = file.pop();
		var fileName = file.shift();
		if (fileName && fileName.substr(fileName.lastIndexOf('.')).toLowerCase() == '.pdf') {
			fileElement += "<div style=\"padding-left:40%\"><a target='_blank' style=\"width:"
					+ width
					+ ";height:"
					+ height
					+ "\" href=fileServer.do?method=getfile&filepath="
					+ filePath
					+ "&fileName="
					+ fileName
					+ ">"
					+ fileName
					+ "</a></div>";
		} else {
			fileElement += "<div style=\"padding-left:40%\"><image style=\"width:"
					+ width
					+ ";height:"
					+ height
					+ "\" src=fileServer.do?method=getfile&filepath="
					+ filePath
					+ " onclick='com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.showImage(\""
					+ filePath + "\")'/></div>";
		}

	}
	Ext.getCmp(position).body.update(fileElement);

};

com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loadImage = function(url,
		position, width, height) {
	var file = url.split("#");
	var filePath = file.pop();
	var fileName = file.shift();
	var images = "<div style=\"padding-left:40%\"><image style=\"width:"
			+ width
			+ ";height:"
			+ height
			+ "\" src=fileServer.do?method=getfile&filepath="
			+ filePath
			+ "&fileName="
			+ fileName
			+ " onclick='com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.showImage(\""
			+ filePath + "\")'/></div>";
	Ext.getCmp(position).body.update(images);
};


com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.approveSubmit = function(){
	var operation=Ext.getCmp("agree.ApproveWithHoldInfo").checked?'0':'1';
	var state=operation=='0'?'3':'5';
	var idea = Ext.getCmp("idea.ApproveWithHoldInfo").getValue();
	if(idea==''){
		Ext.Msg.alert('系统提示','审批意见不能为空！');
		return;
	}
	
	var bankName = Ext.getCmp('bankName.ApproveWithHoldInfo').getValue().split('|').shift();
	var params={
			userId:appConfig.Param.tempParam.split("|")[1],	// 用户ID,客户经理id
			custNo:appConfig.Param.tempParam.split("|")[1],	// 客户号
			insttuId:appConfig.Param.tempParam.split("|")[2],		// 机构号
			insttuTy:appConfig.Param.tempParam.split("|")[3],				// 机构类型
			userName:Ext.getCmp('custName.ApproveWithHoldInfo').getValue(),	
			operation : operation,  
			taskinstanceId : com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.flowId,  
			idea : idea,  
			ps : '代扣签约审批',
			params : '0',
			loanNo:com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.loanNo,
			channel:com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.channel,
			state:state,
			signRecordId:appConfig.Param.tempParam.split("|")[0],
			bankName:bankName
	};
//	 ajaxLoad('jnf/workflow.do?method=submitApprove',params,function(response){
//	    	var respData = Ext.decode(response.responseText);
//	    	if(respData.success){
//	    		Ext.Msg.alert('系统提示',respData.data.rspMsg,function(){
//					com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.closeApprove(); 
//				});
//	    	}else{
//	    		Ext.Msg.alert('系统提示',respData.errMsg);
//	    	}
//	 });
	 
	 Ext.Ajax.request({
		   url: appConfig.baseUrl + "/jnf/workflow.do?method=submitApprove",
		   params: params,
		   success: function(res) {
			   var respData = Ext.decode(res.responseText);
			   if(respData && respData.success){
					Ext.Msg.alert('系统提示',respData.errMsg,function(){
					com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.closeApprove(); 
				});
		    	}else {
					Ext.Msg.alert('系统提示',respData.errMsg);
		    	}
		   }
		});
};
com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.showImage=function(path){
	var showImageWin = new Ext.Window({
	title : "查看原图",
	width:600,
	height:400,
	modal : true,
	closeAction : 'close',
	autoScroll : true,
	html : "<img id='displayImage' src=" + "fileServer.do?method=getfile&filepath="
			+ path + "></img>",

	});
	showImageWin.show();
};

com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.closeApprove = function(){
	   //关掉审批窗口 如果审批页面地址和公共管理平台地址不同会有跨域的问题
	   top.document.getElementById("checkPanelframe").contentWindow.Ext.getCmp("IndexNoticByLoginWindow").hide();
};


