/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.withhold.sign.query.QryWithholdList's method: Javascript class
 * static method be used as ExtJs's event method handler,like
 * 'com.jsjn.jnf.withhold.sign.query.QryWithholdList.method(); this is Class
 * static method' Javasctipt object method be used as get or set object's
 * properties,like
 * 'com.jsjn.jnf.withhold.sign.query.QryWithholdList.prototype.method(); this is
 * object's method' com.jsjn.jnf.withhold.sign.query.QryWithholdList.PANEL is
 * com.jsjn.jnf.withhold.sign.query.QryWithholdList's Singleton instance object .
 * you can get com.jsjn.jnf.withhold.sign.query.QryWithholdList.PANEL's
 * reference by
 * appfram.getInstance('com.jsjn.jnf.withhold.sign.query.QryWithholdList').
 */

var QryWithholdListStart = 0;
appframe
		.afterInstance(
				"com.jsjn.jnf.withhold.sign.query.QryWithholdList",
				function() {
					girdStoreAddExceptionEvent('grid.QryWithholdList',
							"com.jsjn.jnf.withhold.sign.query.QryWithholdList");
					gridSelectionModelVisible('grid.QryWithholdList');

					// 如果是客户经理岗则只能查询本机构的签约信息

					var stationId = appConfig.Session.loginUserInfo.stationId;
					if (com.jsjn.jnf.withhold.sign.query.QryWithholdList
							.isJNG()) {// 金农岗可以查询全部数据
						Ext.getCmp('btnAdd.QryWithholdList').hide();// 隐藏新增按钮
						com.jsjn.jnf.withhold.sign.query.QryWithholdList.custManagerNo = "";
						com.jsjn.jnf.withhold.sign.query.QryWithholdList.insttuId = "";
					} else {
						Ext.getCmp('insttuId.QryWithholdList').hide();// 隐藏机构选择框
						if (stationId.indexOf('400') != -1) {// 非金农的客户经理岗只能查询本机构本人名下的数据
							// 客户经理编号
							com.jsjn.jnf.withhold.sign.query.QryWithholdList.custManagerNo = appConfig.Session.loginUserInfo.id.userId;
							// 小贷公司机构号
							com.jsjn.jnf.withhold.sign.query.QryWithholdList.insttuId = appConfig.Session.loginUserInfo.id.insttuId;
							

						} else if (stationId.indexOf('600') != -1) {// 非金农的会计岗可以查询本机构下所有客户经理名下数据
							Ext.getCmp('btnAdd.QryWithholdList').hide();
							com.jsjn.jnf.withhold.sign.query.QryWithholdList.custManagerNo = "";
							com.jsjn.jnf.withhold.sign.query.QryWithholdList.insttuId = appConfig.Session.loginUserInfo.id.insttuId;

						} else {

							Ext.Msg.alert('系统提示', '当前岗位没有访问权限，请联系管理员！');
							return;
						}
					}

					var grid = Ext.getCmp('grid.QryWithholdList');
					grid.getBottomToolbar().doLoad = function(start) {
						QryWithholdListStart = start;
						this.store.load({
							params : {
								'start' : start,
								'limit' : 10
							}
						});
					};

					// 如果是ie8，手动加载css样式
					if (Ext.isIE8) {
						appframe.loadCss("/js/webuploader/webuploader.css",
								"webuploader");
						appframe.loadCss("/js/webuploader/style.css", "style");
						appframe.loadCss("/js/webuploader/style_back.css",
								"style_back");
						appframe.loadCss("/js/webuploader/style_other.css",
								"style_other");
						appframe
								.loadCss(
										"/com/jsjn/jnf/withhold/sign/add/form/myStyle.css",
										"myStyle");
					}

					// 渲染下拉框 客户类型
					Ext.apply(Ext.getCmp('custType.QryWithholdList'), {
						store : withholdCustStateStore.getStore()
					});
					// 渲染下拉框 证件类型
					Ext.apply(Ext.getCmp('idType.QryWithholdList'), {
						store : withholdCardStateStore.getStore()
					});
					// 渲染下拉框 签约状态
					Ext.apply(Ext.getCmp('state.QryWithholdList'), {
						store : withholdSignStateStore.getStore()
					});

				});

com.jsjn.jnf.withhold.sign.query.QryWithholdList.addParams = function() {
	var custType = Ext.getCmp('custType.QryWithholdList').getValue(); // 客户类型
	var custName = Ext.getCmp('custName.QryWithholdList').getValue(); // 客户名称
	var contNo = Ext.getCmp('contNo.QryWithholdList').getValue(); // 贷款合同号
	var idType = Ext.getCmp('idType.QryWithholdList').getValue(); // 证件类型
	var idNo = Ext.getCmp('idNo.QryWithholdList').getValue(); // 证件号码
	var state = Ext.getCmp('state.QryWithholdList').getValue(); // 签约状态

	var params = {
		limit : 10,
		method : 'getSignInfoList',
		custType : custType,
		custName : "%" + custName + "%",
		contNoExt : "%" + contNo + "%",
		orgNo : com.jsjn.jnf.withhold.sign.query.QryWithholdList.insttuId,
		paperType : idType,
		paperNo : idNo,
		orderType : '1',
		custManagerNo : com.jsjn.jnf.withhold.sign.query.QryWithholdList.custManagerNo,
		signStatus : state
	};

	var gStore = Ext.getCmp('grid.QryWithholdList').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.withhold.sign.query.QryWithholdList.gridRender = function(value,
		cellmeta, record, rowIndex, columnIndex, store) {

	var dataIndex = Ext.getCmp("grid.QryWithholdList").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'operator') {
		// 等待审批（查看）已签约（解约按钮）已解约（重新签约按钮）其他无操作
		var operater = "";
		var state = record.json.state;// 签约状态
		if (com.jsjn.jnf.withhold.sign.query.QryWithholdList.isJNG()) {
			return "<a href=\"#\" onclick=\"com.jsjn.jnf.withhold.sign.query.QryWithholdList.search();\" style=\"vertical-align:bottom; text-decoration:none\">【查看】</a>";
		} else {
			if (state == '3') {// 已签约
				operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.withhold.sign.query.QryWithholdList.realse();\" style=\"vertical-align:bottom; text-decoration:none\">【解约】</a>";
			}
			if (state == '4') {// 已解
				operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.withhold.sign.query.QryWithholdList.reSign();\" style=\"vertical-align:bottom; text-decoration:none\">【重新签约】</a>";
			}
			operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.withhold.sign.query.QryWithholdList.search();\" style=\"vertical-align:bottom; text-decoration:none\">【查看】</a>";
		}
		return operater;
	}
	if (dataIndex == 'custType') {
		return storeFind(withholdCustStateStore, value);
	}
	if (dataIndex == 'idType') {
		return storeFind(withholdCardStateStore, value);
	}
	if (dataIndex == 'repayType') {
		return storeFind(withholdRepayTypeStore, value.trim());
	}
	if (dataIndex == 'osPrcp') {
		return formatMoney(value);
	}
	if (dataIndex == 'state') {
		return storeFind(withholdSignStateStore, value);
	}
	if (dataIndex == 'channel') {
		return storeFind(withholdChannelStore, value);
	}
	return value;
};

/**
 * 新增签约功能
 */
com.jsjn.jnf.withhold.sign.query.QryWithholdList.btnAdd = function() {

	// var win = new Ext.Window({
	// id : "signWithholdForWindow",
	// layout : "fit",
	// title : "新增代扣签约信息",
	// width : 700,
	// height : 500,
	// maximizable : false,// 最大化按钮
	// resizable : false,
	// autoScroll : true,
	// closeAction : "close",
	// autoLoad : {
	// url : "com/jsjn/jnf/withhold/sign/add/form/form.html",
	// url:"/jnf-withhold/com.jsjn.jnf.withhold.sign.query.ApproveWithHoldInfo.view",
	// scripts : true,
	// scope : this,
	// nocache : true,
	// callback : function() {
	// QryCradBin();
	// getParams();
	// initFrontUploer();
	// initBackUploder();
	// initOtherUploder();
	// }
	// }
	// });
	var win = appframe
			.getInstance("com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo");
	// com.jsjn.jnf.withhold.sign.query.AddWithHoldInfo.winInit();
	win.show();

};

/**
 * 点击查询按钮
 */
com.jsjn.jnf.withhold.sign.query.QryWithholdList.btnQuery = function() {
	Ext.getCmp('grid.QryWithholdList').getStore().load();
};

// 获取机构号
com.jsjn.jnf.withhold.sign.query.QryWithholdList.selectRow = function(combo,
		newValue, oldValue) {
	com.jsjn.jnf.withhold.sign.query.QryWithholdList.insttuId = newValue;
};

/**
 * 设置全局变量
 */
com.jsjn.jnf.withhold.sign.query.QryWithholdList.signRecordId = '';

/**
 * 解约功能
 * 
 */
com.jsjn.jnf.withhold.sign.query.QryWithholdList.realse = function() {

	Ext.MessageBox.confirm("提示", '您确定要解约吗？', function(btn) {
		if (btn == 'yes') {
			var record = Ext.getCmp('grid.QryWithholdList').getSelectionModel()
					.getSelected();
			Ext.Ajax.request({
				params : {
					aid : record.data.aid,
					channel : record.data.channel,
					loanNo : record.data.loanNo,
					insttuId : record.data.insttuId,
					signRecordId : record.data.signRecordId,
					mobile : record.data.mobile,
					insttuName : record.data.insttuName,
					custName : record.data.custName,
					cardNo : record.data.cardNo,
					contNo : record.data.contNo
				},
				method : "POST",
				url : appConfig.baseUrl + '/jnf/sign.do?method=cancel',
				waitMsg : '正在处理数据...',
				waitTitle : '提示',
				success : function(response) {
					var result = Ext.decode(response.responseText);
					if (result.success) {

						Ext.MessageBox.alert('提示', result.errMsg);
						// 刷新列表
						Ext.getCmp("grid.QryWithholdList").getStore().load();
					} else {

						Ext.MessageBox.alert('提示', result.errMsg);
					}
				}
			});

		}
	});
};
/**
 * 重新签约功能
 * 
 */
com.jsjn.jnf.withhold.sign.query.QryWithholdList.reSign = function() {

	var record = Ext.getCmp('grid.QryWithholdList').getSelectionModel()
			.getSelected();
	appConfig.Param.signRecordId = record.json.signRecordId;
	var win = appframe
			.getInstance("com.jsjn.jnf.withhold.sign.query.WithHoldResign");
	win.show();
	// var win = new Ext.Window({
	// id : "ReSignWithholdForWindow",
	// layout : "fit",
	// title : "重新签约功能",
	// width : 700,
	// height : 500,
	// maximizable : false,// 最大化按钮
	// resizable : false,
	// autoScroll : true,
	// autoLoad : {
	// url : "com/jsjn/jnf/withhold/sign/query/reSign/form_reSign.html",
	// scripts : true,
	// scope : this,
	// nocache : true,
	// callback:function(){
	// load();
	// QryCradBin_reSign();
	// initFrontUploer();
	// initBackUploder();
	// initOtherUploder();
	// }
	// }
	// });
	// win.show();

};
/**
 * 查看功能
 * 
 */

com.jsjn.jnf.withhold.sign.query.QryWithholdList.search = function() {
	 var record = Ext.getCmp('grid.QryWithholdList').getSelectionModel().getSelected();
	 com.jsjn.jnf.withhold.sign.query.QryWithholdList.signRecordId = record.json.signRecordId;
	 appConfig.Param.tempParam = record.json.signRecordId;
	 var win = appframe.getInstance("com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo");
	 com.jsjn.jnf.withhold.sign.query.ViewWithHoldInfo.winInit();
	 win.x='0';
	 win.y='0';
	 win.show();
};

com.jsjn.jnf.withhold.sign.query.QryWithholdList.btnReset = function(btn, event) {
	Ext.getCmp('form.QryWithholdList').getForm().reset();
	com.jsjn.jnf.withhold.sign.query.QryWithholdList.insttuId = '';

};
/**
 * 判断是否是金农岗 true 表示为金农岗 否则为客户经理
 */
com.jsjn.jnf.withhold.sign.query.QryWithholdList.isJNG = function() {
	// 如果是客户经理岗则只能查询本机构的签约信息
	return appConfig.Session.loginUserInfo.id.userId.indexOf('990000001') != -1;
};
