/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.fee.FeeAddConfig's method: Javascript class static method be
 * used as ExtJs's event method handler,like
 * 'com.jsjn.jnf.fee.FeeAddConfig.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like
 * 'com.jsjn.jnf.fee.FeeAddConfig.prototype.method(); this is object's method'
 * com.jsjn.jnf.fee.FeeAddConfig.main method is the beginning of all.
 * com.jsjn.jnf.fee.FeeAddConfig.WINDOW iscom.jsjn.jnf.fee.FeeAddConfig's
 * Singleton instance object . you can get com.jsjn.jnf.fee.FeeAddConfig.WINDOW
 * reference by appfram.getInstance('com.jsjn.jnf.fee.FeeAddConfig').
 */

var FeeAddConfigInsttuId = '', FeeAddConfigMid = '';
appframe.afterInstance("com.jsjn.jnf.fee.FeeAddConfig", function(panel) {
    if (panel) {
        // 渲染收费项目下拉框
        Ext.apply(Ext.getCmp('channel.FeeAddConfig'), {
            store : withholdChannelStore.getStore()
        });

        // 渲染下拉框
        Ext.apply(Ext.getCmp('businessType.FeeAddConfig'), {
            store : businessTypeStore.getStore()
        });
    }
});

// 重置
com.jsjn.jnf.fee.FeeAddConfig.btnReset = function() {
    Ext.getCmp('form.FeeAddConfig').getForm().reset();
    FeeAddConfigInsttuId = '';
    FeeAddConfigMid = '';
};
// 保存
com.jsjn.jnf.fee.FeeAddConfig.btnSave = function() {
    // 收费项目
    var businessType = Ext.getCmp('businessType.FeeAddConfig').getValue();
    var channel = Ext.getCmp('channel.FeeAddConfig').getValue();
    // 开始时间
    var startTime = Ext.getCmp('startTime.FeeAddConfig').getRawValue();
    // 结束时间
    var endTime = Ext.getCmp('endTime.FeeAddConfig').getRawValue();
    // 费率
    var fee = Ext.getCmp('price.FeeAddConfig').getValue();
    // 是否全局费率
    var isGlobal = Ext.getCmp('isGlobal.FeeAddConfig').getValue();

    if (valueIsEmpty(FeeAddConfigMid)) {
        Ext.Msg.alert('系统提示', '商户名称不能为空!');
        return false;
    }
    if (!isGlobal && valueIsEmpty(FeeAddConfigInsttuId)) {
        Ext.Msg.alert('系统提示', '机构名称不能为空!');
        return false;
    }
    if (valueIsEmpty(channel)) {
        Ext.Msg.alert('系统提示', '渠道不能为空!');
        return false;
    }
    if (valueIsEmpty(businessType)) {
        Ext.Msg.alert('系统提示', '收费项目不能为空!');
        return false;
    }
    if (valueIsEmpty(fee)) {
        Ext.Msg.alert('系统提示', '费率不能为空!');
        return false;
    }
    if (valueIsEmpty(startTime)) {
        Ext.Msg.alert('系统提示', '开始时间不能为空!');
        return false;
    }
    if (valueIsEmpty(endTime)) {
        Ext.Msg.alert('系统提示', '结束时间不能为空!');
        return false;
    }
    if (startTime >= endTime) {
        Ext.Msg.alert('系统提示', '开始时间不能大于结束时间!');
        return false;
    }

    var url = 'jnf/feeConfigService.do?method=addFeeConfig';
    var param = {
        'mid' : FeeAddConfigMid,
        'orgNo' : FeeAddConfigInsttuId,
        'channel' : channel,
        'startTime' : startTime,
        'endTime' : endTime,
        'feeType' : businessType,
        'fee' : fee,
    };
    ajaxLoad(url, param, '', '', '', function(response) {
        var success = Ext.decode(response.responseText).success;
        var resMsg = Ext.decode(response.responseText).resMsg;
        if (success) {
            Ext.Msg.alert("系统提示", "新增成功！", function() {
                com.jsjn.jnf.fee.FeeAddConfig.btnReset();
                com.jsjn.jnf.fee.FeeConfig.btnQuery();
            });
        } else {
            Ext.Msg.alert("系统提示", "新增失败！" + resMsg);
        }

    });
};
/**
 * 选择机构
 */
com.jsjn.jnf.fee.FeeAddConfig.InsttuSelectRow = function(combo, newValue,
        oldValue) {
    FeeAddConfigInsttuId = newValue;
};

/**
 * 选择商户
 */
com.jsjn.jnf.fee.FeeAddConfig.BusinessSelectRow = function(combo, newValue,
        oldValue) {
    FeeAddConfigMid = newValue;
    var gridStore = Ext.getCmp('insttuName.FeeAddConfig').Gridstore;
    gridStore.baseParams.mId = newValue;
    gridStore.load();
};

com.jsjn.jnf.fee.FeeAddConfig.checkGlobal = function(checkbox, checked) {
    Ext.getCmp('insttuName.FeeAddConfig').setDisabled(checked);
};
