/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.fee.FeeConfig's method: Javascript class static method be used
 * as ExtJs's event method handler,like 'com.jsjn.jnf.fee.FeeConfig.method();
 * this is Class static method' Javasctipt object method be used as get or set
 * object's properties,like 'com.jsjn.jnf.fee.FeeConfig.prototype.method(); this
 * is object's method' com.jsjn.jnf.fee.FeeConfig.PANEL is
 * com.jsjn.jnf.fee.FeeConfig's Singleton instance object . you can get
 * com.jsjn.jnf.fee.FeeConfig.PANEL's reference by
 * appfram.getInstance('com.jsjn.jnf.fee.FeeConfig').
 */
var FeeConfigInsttuId = '', FeeConfigMid = '';
appframe.afterInstance("com.jsjn.jnf.fee.FeeConfig", function(panel) {
    if (panel) {
        // 渲染收费项目下拉框
        Ext.apply(Ext.getCmp('channel.FeeConfig'), {
            store : withholdChannelStore.getStore()
        });

        // 渲染下拉框
        Ext.apply(Ext.getCmp('businessType.FeeConfig'), {
            store : businessTypeStore.getStore()
        });
    }
});

// 重置
com.jsjn.jnf.fee.FeeConfig.btnReset = function() {
    Ext.getCmp('form.FeeConfig').getForm().reset();
    FeeConfigInsttuId = '';
    FeeConfigMid = '';
};
// 查询
com.jsjn.jnf.fee.FeeConfig.btnQuery = function() {
    // 业务类型
    var businessType = Ext.getCmp('businessType.FeeConfig').getValue();
    // 渠道
    var channel = Ext.getCmp('channel.FeeConfig').getValue();

    var store = Ext.getCmp('grid.FeeConfig').getStore();
    store.baseParams.mid = FeeConfigMid;
    store.baseParams.orgNo = FeeConfigInsttuId;
    store.baseParams.feeType = businessType;
    store.baseParams.channel = channel;
    store.load();
};
/**
 * 选择机构
 */
com.jsjn.jnf.fee.FeeConfig.InsttuSelectRow = function(combo, newValue, oldValue) {
    FeeConfigInsttuId = newValue;
};

/**
 * 选择商户
 */
com.jsjn.jnf.fee.FeeConfig.BusinessSelectRow = function(combo, newValue,
        oldValue) {
    FeeConfigMid = newValue;
    var gridStore = Ext.getCmp('insttuName.FeeConfig').Gridstore;
    gridStore.baseParams.mId = newValue;
    gridStore.load();
};

com.jsjn.jnf.fee.FeeConfig.checkGlobal = function(checkbox, checked) {
    Ext.getCmp('insttuName.FeeConfig').setDisabled(checked);
};

com.jsjn.jnf.fee.FeeConfig.gridRender = function(value, cellmeta, record,
        rowIndex, columnIndex, store) {
    var dataIndex = Ext.getCmp("grid.FeeConfig").getColumnModel().getDataIndex(
            columnIndex);
    if (dataIndex == 'xh') {
        return rowIndex + 1;
    } else if (dataIndex == 'startTime' || dataIndex == 'endTime') {
        return value.format('Y-m-d');
    } else if (dataIndex == 'fee') {
        return Ext.util.Format.numberRenderer('0,0.00')(value);
    } else if (dataIndex == 'feeType') {
        return storeFind(businessTypeStore, value);
    } else if (dataIndex == 'channel') {
        return storeFind(withholdChannelStore, value);
    } else {
        return value;
    }
};
/**
 * 新增计费参数
 */
com.jsjn.jnf.fee.FeeConfig.addConfig = function(button, event) {
    var win = appframe.getInstance("com.jsjn.jnf.fee.FeeAddConfig");
    win.show();
};