/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.fee.FeeRealNameAuthDetail's method: Javascript class static
 * method be used as ExtJs's event method handler,like
 * 'com.jsjn.jnf.fee.FeeRealNameAuthDetail.method(); this is Class static
 * method' Javasctipt object method be used as get or set object's
 * properties,like 'com.jsjn.jnf.fee.FeeRealNameAuthDetail.prototype.method();
 * this is object's method' com.jsjn.jnf.fee.FeeRealNameAuthDetail.main method
 * is the beginning of all. com.jsjn.jnf.fee.FeeRealNameAuthDetail.WINDOW
 * iscom.jsjn.jnf.fee.FeeRealNameAuthDetail's Singleton instance object . you
 * can get com.jsjn.jnf.fee.FeeRealNameAuthDetail.WINDOW reference by
 * appfram.getInstance('com.jsjn.jnf.fee.FeeRealNameAuthDetail').
 */
com.jsjn.jnf.fee.FeeRealNameAuthDetail.gridRender = function(value, cellmeta,
        record, rowIndex, columnIndex, store) {
    var dataIndex = Ext.getCmp("grid.FeeRealNameAuthDetail").getColumnModel()
            .getDataIndex(columnIndex);
    if (dataIndex == 'xh') {
        return rowIndex + 1;
    } else if (dataIndex == 'modified') {
        return value.format('Y-m-d H:i:s');
    } else if (dataIndex == 'fee') {
        return Ext.util.Format.numberRenderer('0,0.00')(value);
    } else {

        return value;
    }
};

// 导出Excel
com.jsjn.jnf.fee.FeeRealNameAuthDetail.exportExcel = function() {
    console.log('FeeRealNameAuthDetail');
    var orgNo = Ext.getCmp("orgNo.FeeRealNameAuthDetail").getValue();
    var startTime = Ext.getCmp("startTime.FeeRealNameAuthDetail").getValue();
    var endTime = Ext.getCmp("endTime.FeeRealNameAuthDetail").getValue();
    var fileName = Ext.getCmp("fileName.FeeRealNameAuthDetail").getValue();
    var url = appConfig.baseUrl
            + '/jnf/FeeComInfoAction.do?method=expertFeeRealName&startTime='
            + startTime + '&endTime=' + endTime + '&orgNo=' + orgNo
            + '&fileName=' + fileName;
    window.open(url);
};