/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.fee.FeeWithholdDetail's method: Javascript class static method
 * be used as ExtJs's event method handler,like
 * 'com.jsjn.jnf.fee.FeeWithholdDetail.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like
 * 'com.jsjn.jnf.fee.FeeWithholdDetail.prototype.method(); this is object's
 * method' com.jsjn.jnf.fee.FeeWithholdDetail.main method is the beginning of
 * all. com.jsjn.jnf.fee.FeeWithholdDetail.WINDOW
 * iscom.jsjn.jnf.fee.FeeWithholdDetail's Singleton instance object . you can
 * get com.jsjn.jnf.fee.FeeWithholdDetail.WINDOW reference by
 * appfram.getInstance('com.jsjn.jnf.fee.FeeWithholdDetail').
 */

com.jsjn.jnf.fee.FeeWithholdDetail.gridRender = function(value, cellmeta,
        record, rowIndex, columnIndex, store) {
    var dataIndex = Ext.getCmp("grid.FeeWithholdDetail").getColumnModel()
            .getDataIndex(columnIndex);
    if (dataIndex == 'xh') {
        return rowIndex + 1;
    } else if (dataIndex == 'modified') {
        return value.format('Y-m-d H:i:s');
    } else if (dataIndex == 'fee' || dataIndex == 'amount') {
        return Ext.util.Format.numberRenderer('0,0.00')(value);
    } else {

        return value;
    }
};

// 导出Excel
com.jsjn.jnf.fee.FeeWithholdDetail.exportExcel = function() {
    console.log('FeeWithholdDetail');
    var orgNo = Ext.getCmp("orgNo.FeeWithholdDetail").getValue();
    var startTime = Ext.getCmp("startTime.FeeWithholdDetail").getValue();
    var endTime = Ext.getCmp("endTime.FeeWithholdDetail").getValue();
    var fileName = Ext.getCmp("fileName.FeeWithholdDetail").getValue();
    var url = appConfig.baseUrl
            + '/jnf/FeeComInfoAction.do?method=expertFeeWithhold&startTime='
            + startTime + '&endTime=' + endTime + '&orgNo=' + orgNo
            + '&fileName=' + fileName;
    window.open(url);
};