/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.fee.QryTotalFeeListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.fee.QryTotalFeeListMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.fee.QryTotalFeeListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.fee.QryTotalFeeListMgr.PANEL is com.jsjn.jnf.fee.QryTotalFeeListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.fee.QryTotalFeeListMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.fee.QryTotalFeeListMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.fee.QryTotalFeeListMgr",function() {
		girdStoreAddExceptionEvent('grid.QryTotalFeeListMgr',
		"com.jsjn.jnf.fee.QryTotalFeeListMgr");
		
});


com.jsjn.jnf.fee.QryTotalFeeListMgr.addParams = function() {
	var mname = Ext.getCmp('mname.QryTotalFeeListMgr').getValue();	//商户名称
	var feeType = Ext.getCmp('feeType.QryTotalFeeListMgr').getValue();	//收费项目
	var startTime = Ext.getCmp('startTime.QryTotalFeeListMgr').getRawValue(); //开始时间
	var endTime = Ext.getCmp('endTime.QryTotalFeeListMgr').getRawValue(); //结束时间
	var insttuName = Ext.getCmp('insttuName.QryTotalFeeListMgr').getValue(); //机构名称
	
	if(startTime == '' ){
		startTime = com.jsjn.jnf.fee.QryTotalFeeListMgr.firstDay();
		Ext.getCmp('startTime.QryTotalFeeListMgr').setValue(startTime);
	}
	if(endTime == '' ){
		endTime = com.jsjn.jnf.fee.QryTotalFeeListMgr.lastDay();
		Ext.getCmp('endTime.QryTotalFeeListMgr').setValue(endTime);
	}
	com.jsjn.jnf.fee.startTime = startTime;
	com.jsjn.jnf.fee.endTime = endTime;
	
	if( startTime != '' && endTime != '' && startTime > endTime){
		Ext.Msg.alert('系统提示', '开始时间不能大于结束时间');
		return false;
	}
	
	var params = {
			mname : mname,
			feeType : feeType,
			startTime : startTime,
			endTime : endTime,
			insttuName : insttuName
	};
	
	var gStore = Ext.getCmp('grid.QryTotalFeeListMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.fee.QryTotalFeeListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var valid = record.json.valid;//数据是否被篡改
	
	var dataIndex = Ext.getCmp("grid.QryTotalFeeListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'operator') {
		var operater = "";
		if(valid == false){
			operater += "警告：数据被篡改";
		}else{
			operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.fee.QryTotalFeeListMgr.accountDetail();\" style=\"vertical-align:bottom; text-decoration:none\">【对账详情】</a>";
		}
		return operater;
	}
	if (dataIndex == 'startTime') {
		return com.jsjn.jnf.fee.startTime;
	}
	if (dataIndex == 'endTime') {
		return com.jsjn.jnf.fee.endTime;
	}
	if (dataIndex == 'price') {
		return formatMoney(value);
	}
	if (dataIndex == 'totalMoney') {
		return formatMoney(value);
	}
	if (dataIndex == 'insttuName') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	
	return value;
};

/**
 *点击查询按钮 
 */
com.jsjn.jnf.fee.QryTotalFeeListMgr.btnQuery = function() {

	Ext.getCmp('grid.QryTotalFeeListMgr').getStore().load();

};

/**
 *点击重置按钮 
 */
com.jsjn.jnf.fee.QryTotalFeeListMgr.btnReset = function() {
	Ext.getCmp('form.QryTotalFeeListMgr').getForm().reset();
};


com.jsjn.jnf.fee.QryTotalFeeListMgr.firstDay = function(){
	
	var date_ = new Date();  
	var year = date_.getFullYear();  
	var month = date_.getMonth() + 1;  
	if(month < 10){
		month = '0'+month;
	}
//	var firstdate = year + '-' + month + '-01'  
//	var month_first = formatDate(parseDate(firstdate),"yyyy-MM-dd")+" 00:00:00";  
	return year + '' + month + '' + '01';
};

com.jsjn.jnf.fee.QryTotalFeeListMgr.lastDay = function(){
	
	var date_ = new Date();  
	var year = date_.getFullYear();  
	var month = date_.getMonth() + 1;  
	if(month < 10){
		month = '0'+month;
	}
	var day = new Date(year,month,0);      
//	var lastdate = year + '-' + month + '-' + day.getDate();  
//	var month_last = formatDate(parseDate(lastdate),"yyyy-MM-dd")+" 24:00:00";
	return year + '' + month + '' + day.getDate();
	
};

com.jsjn.jnf.fee.QryTotalFeeListMgr.accountDetail = function(){
	
var record = Ext.getCmp('grid.QryTotalFeeListMgr').getSelectionModel().getSelected();
	
	record.json.startTime = com.jsjn.jnf.fee.startTime;
	record.json.endTime = com.jsjn.jnf.fee.endTime;

	var win = appframe.getInstance("com.jsjn.jnf.fee.AccountsDetailMgr");
	
	win.show();
	
	com.jsjn.jnf.fee.AccountsDetailMgr.panelInit(record);
	
};

com.jsjn.jnf.fee.QryTotalFeeListMgr.exportExcel = function(){
	
	if(checkForm('form.QryTotalFeeListMgr')){
		
		var mname = Ext.getCmp('mname.QryTotalFeeListMgr').getValue();	//商户名称
		var feeType = Ext.getCmp('feeType.QryTotalFeeListMgr').getValue();	//收费项目
		var startTime = Ext.getCmp('startTime.QryTotalFeeListMgr').getRawValue(); //开始时间
		var endTime = Ext.getCmp('endTime.QryTotalFeeListMgr').getRawValue(); //结束时间
		var insttuName = Ext.getCmp('insttuName.QryTotalFeeListMgr').getValue(); //机构名称
		
		
		if( startTime != '' && startTime != '' && endTime > endTime){
			Ext.Msg.alert('系统提示', '开始时间不能大于结束时间');
			return false;
		}
		
		var url = appConfig.baseUrl + '/jnf/FeeComInfoAction.do?method=qryTotalFee&mname='+mname+'&feeType='+feeType+'&startTime='+startTime+'&endTime='+endTime+'&insttuName='+insttuName+'&_isUnLoad=1';
		window.open(url);
	}
	
};
