/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.fee.AccountsDetailMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.fee.AccountsDetailMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.fee.AccountsDetailMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.fee.AccountsDetailMgr.main method is the beginning of all.
 * com.jsjn.jnf.fee.AccountsDetailMgr.WINDOW  iscom.jsjn.jnf.fee.AccountsDetailMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.fee.AccountsDetailMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.fee.AccountsDetailMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.fee.AccountsDetailMgr",function() {
		girdStoreAddExceptionEvent('grid.AccountsDetailMgr',
		"com.jsjn.jnf.fee.AccountsDetailMgr");
		
});

com.jsjn.jnf.fee.AccountsDetailMgr.panelInit = function(record){
	com.jsjn.jnf.fee.mid = record.json.mid;			//商户号
	com.jsjn.jnf.fee.orgNo = record.json.orgNo;		//机构号
	var startTime = record.json.startTime;	//开始时间
	var endTime = record.json.endTime;		//结束时间
	var mname = record.json.mname;			//商户名称
	var insttuName = record.json.insttuName;		//机构名称
	
	Ext.getCmp('mname.AccountsDetailMgr').setValue(mname);
	Ext.getCmp('insttuName.AccountsDetailMgr').setValue(insttuName);
	Ext.getCmp('startTime.AccountsDetailMgr').setValue(startTime);
	Ext.getCmp('endTime.AccountsDetailMgr').setValue(endTime);
	
};

com.jsjn.jnf.fee.AccountsDetailMgr.addParams = function() {
	var mid = com.jsjn.jnf.fee.mid;		//商户号
	var orgNo = com.jsjn.jnf.fee.orgNo;	//机构号
	var startTime = Ext.getCmp('startTime.AccountsDetailMgr').getRawValue(); //开始时间
	var endTime = Ext.getCmp('endTime.AccountsDetailMgr').getRawValue(); //结束时间
	
	if( startTime != '' && endTime != '' && startTime > endTime){
		Ext.Msg.alert('系统提示', '开始时间不能大于结束时间');
		return false;
	}
	
	var params = {
			mid : mid,
			orgNo : orgNo,
			created : startTime,
			modified : endTime
	};
	
	var gStore = Ext.getCmp('grid.AccountsDetailMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.fee.AccountsDetailMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var dataIndex = Ext.getCmp("grid.AccountsDetailMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'exception') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	
	return value;
};

com.jsjn.jnf.fee.AccountsDetailMgr.exportExcel = function(){
	
	var mid = com.jsjn.jnf.fee.mid;		//商户号
	var orgNo = com.jsjn.jnf.fee.orgNo;	//机构号
	var startTime = Ext.getCmp('startTime.AccountsDetailMgr').getRawValue(); //开始时间
	var endTime = Ext.getCmp('endTime.AccountsDetailMgr').getRawValue(); //结束时间
	
	var url = appConfig.baseUrl + '/jnf/FeeComInfoAction.do?method=queryAccount&mid='+mid+'&orgNo='+orgNo+'&startTime='+startTime+'&endTime='+endTime+'&_isUnLoad=1';
	window.open(url);
	
};

com.jsjn.jnf.fee.AccountsDetailMgr.close = function(){
	com.jsjn.jnf.fee.AccountsDetailMgr.WINDOW.hide();
};