/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.fee.FeeXmlDetailMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.fee.FeeXmlDetailMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.fee.FeeXmlDetailMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.fee.FeeXmlDetailMgr.main method is the beginning of all.
 * com.jsjn.jnf.fee.FeeXmlDetailMgr.WINDOW  iscom.jsjn.jnf.fee.FeeXmlDetailMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.fee.FeeXmlDetailMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.fee.FeeXmlDetailMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.fee.FeeXmlDetailMgr", function() {
	
});

com.jsjn.jnf.fee.FeeXmlDetailMgr.panelInit = function(record){
	var inputXml = record.data.inputXml;			//支付订单编号
	var outputXml = record.data.outputXml;			//支付订单编号
	
	Ext.getCmp('inputXml.FeeXmlDetailMgr').setValue(inputXml);
	Ext.getCmp('outputXml.FeeXmlDetailMgr').setValue(outputXml);
	
};


/**
 * 关闭
 */
com.jsjn.jnf.fee.FeeXmlDetailMgr.close = function(){
	com.jsjn.jnf.fee.FeeXmlDetailMgr.WINDOW.hide();
};