/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.fee.QryFeeXmlFlowListMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.method(); this is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.PANEL is com.jsjn.jnf.fee.QryFeeXmlFlowListMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.PANEL's reference  by appfram.getInstance('com.jsjn.jnf.fee.QryFeeXmlFlowListMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.fee.QryFeeXmlFlowListMgr",function() {
		girdStoreAddExceptionEvent('grid.QryFeeXmlFlowListMgr',
		"com.jsjn.jnf.fee.QryFeeXmlFlowListMgr");
		
		//渲染下拉框
		Ext.apply(Ext.getCmp('bflag.QryFeeXmlFlowListMgr'), {
			store : interBussStateStore.getStore()
		});	
		
		Ext.apply(Ext.getCmp('state.QryFeeXmlFlowListMgr'), {
			store : interfaceStateStore.getStore()
		});	
		
});

com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.addParams = function() {
	var mname = Ext.getCmp('mname.QryFeeXmlFlowListMgr').getValue();	//商户名称
	var custName = Ext.getCmp('custName.QryFeeXmlFlowListMgr').getValue();	//机构名称
	var reqTimeMin = Ext.getCmp('reqTimeMin.QryFeeXmlFlowListMgr').getRawValue(); //调用时间（起）
	var reqTimeMax = Ext.getCmp('reqTimeMax.QryFeeXmlFlowListMgr').getRawValue(); //调用时间（止）
	var state = Ext.getCmp('state.QryFeeXmlFlowListMgr').getValue(); //调用接口状态
	var bflag = Ext.getCmp('bflag.QryFeeXmlFlowListMgr').getValue(); //业务状态
	
	
	if( reqTimeMin != '' && reqTimeMax != '' && reqTimeMin > reqTimeMax){
		Ext.Msg.alert('系统提示', '调用时间（起）不能大于调用时间（止）');
		return false;
	}
	
	var params = {
			mname : mname,
			beginTime : reqTimeMin,
			custName : custName,
			overTime : reqTimeMax,
			state : state,
			bflag : bflag
	};
	
	var gStore = Ext.getCmp('grid.QryFeeXmlFlowListMgr').getStore();
	// 判断grid的store中存在查询参数和查询结果
	if (undefined != gStore && gStore.getCount() > 0) {
		gStore.removeAll(); // 清空表格store中的查询参数
	}
	gStore.baseParams = params;

};

com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.gridRender = function(value, cellmeta,
		record, rowIndex, columnIndex, store) {
	
	var valid = record.json.valid;//数据是否被篡改
	
	var dataIndex = Ext.getCmp("grid.QryFeeXmlFlowListMgr").getColumnModel()
			.getDataIndex(columnIndex);
	if (dataIndex == 'cplsh') {
		return rowIndex + 1;
	}
	if (dataIndex == 'operator') {
		var operater = "";
		if(valid == false){
			operater += "警告：数据被篡改";
		}else{
			operater += "<a href=\"#\" onclick=\"com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.xmlDetail();\" style=\"vertical-align:bottom; text-decoration:none\">【报文详情】</a>";
		}
		return operater;
	}
	if (dataIndex == 'bflag') {
		return storeFind(interBussStateStore, value);
	}
	if (dataIndex == 'state') {
		return storeFind(interfaceStateStore, value);
	}
	if (dataIndex == 'fee') {
		return formatMoney(value);
	}
	if (dataIndex == 'custName') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	if (dataIndex == 'exception') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	if (dataIndex == 'reason') {
		cellmeta.attr = "ext:qtip= '"+value+"'";
	}
	
	return value;
};

/**
 *点击查询按钮 
 */
com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.btnQuery = function() {

	Ext.getCmp('grid.QryFeeXmlFlowListMgr').getStore().load();

};

/**
 *点击重置按钮 
 */
com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.btnReset = function() {
	Ext.getCmp('form.QryFeeXmlFlowListMgr').getForm().reset();
};

/**
 * 查询xml报文详情
 */
com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.xmlDetail = function() {
	
	var record = Ext.getCmp('grid.QryFeeXmlFlowListMgr').getSelectionModel().getSelected();
	
	var win = appframe.getInstance("com.jsjn.jnf.fee.FeeXmlDetailMgr");
	
	win.show();
	
	com.jsjn.jnf.fee.FeeXmlDetailMgr.panelInit(record);
};

com.jsjn.jnf.fee.QryFeeXmlFlowListMgr.exportInfo = function(){
//	Ext.Msg.alert("系统提示","未提供本功能");
	if(checkForm('form.QryFeeXmlFlowListMgr')){
		
		var mname = Ext.getCmp('mname.QryFeeXmlFlowListMgr').getValue();	//商户名称
		var custName = Ext.getCmp('custName.QryFeeXmlFlowListMgr').getValue();	//机构名称
		var reqTimeMin = Ext.getCmp('reqTimeMin.QryFeeXmlFlowListMgr').getRawValue(); //调用时间（起）
		var reqTimeMax = Ext.getCmp('reqTimeMax.QryFeeXmlFlowListMgr').getRawValue(); //调用时间（止）
		var state = Ext.getCmp('state.QryFeeXmlFlowListMgr').getValue(); //调用接口状态
		var bflag = Ext.getCmp('bflag.QryFeeXmlFlowListMgr').getValue(); //业务状态
		
		
		if( reqTimeMin != '' && reqTimeMax != '' && reqTimeMin > reqTimeMax){
			Ext.Msg.alert('系统提示', '调用时间（起）不能大于调用时间（止）');
			return false;
		}
		
		var url = appConfig.baseUrl + '/jnf/FeeComInfoAction.do?method=expertFeeXml&mname='+mname+'&custName='+custName+'&reqTimeMin='+reqTimeMin+'&reqTimeMax='+reqTimeMax+'&state='+state+'&bflag='+bflag+'&_isUnLoad=1';
		window.open(url);
	}

};