/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.payment.PaymentInfoDetailMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.payment.PaymentInfoDetailMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.payment.PaymentInfoDetailMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.payment.PaymentInfoDetailMgr.main method is the beginning of all.
 * com.jsjn.jnf.payment.PaymentInfoDetailMgr.WINDOW  iscom.jsjn.jnf.payment.PaymentInfoDetailMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.payment.PaymentInfoDetailMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.payment.PaymentInfoDetailMgr'). 
 */

appframe.afterInstance("com.jsjn.jnf.payment.PaymentInfoDetailMgr", function() {
	
});

com.jsjn.jnf.payment.PaymentInfoDetailMgr.panelInit = function(record){
	var orderNo = record.data.orderNo;			//支付订单编号
	var tradeNo = record.data.tradeNo;			//交易订单编号
	var payAccount = record.data.payAccount;	//付款账号
	var payer = record.data.payer;				//付款人
	var collAccount = record.data.collAccount;	//收款账号
	var payee = record.data.payee;				//收款人
	var amount = record.data.amount;			//支付金额
	var channel = record.data.channel;			//支付渠道
	var status = record.data.status;			//支付状态
	var failReason = record.data.failReason;	//失败原因
	var modified = record.data.modified;		//交易时间
	
	Ext.getCmp('orderNo.PaymentInfoDetailMgr').setValue(orderNo);
	Ext.getCmp('tradeNo.PaymentInfoDetailMgr').setValue(tradeNo);
	Ext.getCmp('payAccount.PaymentInfoDetailMgr').setValue(payAccount);
	Ext.getCmp('payer.PaymentInfoDetailMgr').setValue(payer);
	Ext.getCmp('collAccount.PaymentInfoDetailMgr').setValue(collAccount);
	Ext.getCmp('payee.PaymentInfoDetailMgr').setValue(payee);
	Ext.getCmp('amount.PaymentInfoDetailMgr').setValue(formatMoney(amount));
	Ext.getCmp('channel.PaymentInfoDetailMgr').setValue(storeFind(paymentChannelStore, channel));
	Ext.getCmp('status.PaymentInfoDetailMgr').setValue(storeFind(paymentStatusStore, status));
	Ext.getCmp('failReason.PaymentInfoDetailMgr').setValue(failReason);
	Ext.getCmp('modified.PaymentInfoDetailMgr').setValue(modified.substr(0,10));
	
};

/**
 * 关闭
 */
com.jsjn.jnf.payment.PaymentInfoDetailMgr.close = function(){
	com.jsjn.jnf.payment.PaymentInfoDetailMgr.WINDOW.hide();
};
