/**
 * generated by JNGU-2012-ExtPlugins.
 * please  write here  com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr's method:
 * Javascript class static method be used as ExtJs's event method handler,like 'com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.method(); this  is Class static method'
 * Javasctipt object method be used as get or set object's properties,like 'com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.prototype.method(); this is object's method'
 * com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.main method is the beginning of all.
 * com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.WINDOW  iscom.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr's  Singleton instance object .
 * you can get com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.WINDOW reference  by appfram.getInstance('com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr'). 
 */
appframe.afterInstance("com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr", function() {
	
});

com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.panelInit = function(record){
	var orderNo = record.data.orderNo;			//支付订单编号
	var tradeNo = record.data.tradeNo;			//交易订单编号
	var payAccount = record.data.payAccount;	//付款账号
	var payer = record.data.payer;				//付款人
	var collAccount = record.data.collAccount;	//收款账号
	var payee = record.data.payee;				//收款人
	var amount = record.data.amount;			//支付金额
	var channel = record.data.channel;			//支付渠道
	var status = record.data.status;			//支付状态
	var failReason = record.data.failReason;	//失败原因
	var modified = record.data.modified;		//交易时间
	
	Ext.getCmp('orderNo.PaymentExceptionInfoDetailMgr').setValue(orderNo);
	Ext.getCmp('tradeNo.PaymentExceptionInfoDetailMgr').setValue(tradeNo);
	Ext.getCmp('payAccount.PaymentExceptionInfoDetailMgr').setValue(payAccount);
	Ext.getCmp('payer.PaymentExceptionInfoDetailMgr').setValue(payer);
	Ext.getCmp('collAccount.PaymentExceptionInfoDetailMgr').setValue(collAccount);
	Ext.getCmp('payee.PaymentExceptionInfoDetailMgr').setValue(payee);
	Ext.getCmp('amount.PaymentExceptionInfoDetailMgr').setValue(formatMoney(amount));
	Ext.getCmp('channel.PaymentExceptionInfoDetailMgr').setValue(storeFind(paymentChannelStore, channel));
	Ext.getCmp('status.PaymentExceptionInfoDetailMgr').setValue(storeFind(paymentStatusStore, status));
	Ext.getCmp('failReason.PaymentExceptionInfoDetailMgr').setValue(failReason);
	Ext.getCmp('modified.PaymentExceptionInfoDetailMgr').setValue(modified.substr(0,10));
	
};

/**
 * 关闭
 */
com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.close = function(){
	com.jsjn.jnf.payment.PaymentExceptionInfoDetailMgr.WINDOW.hide();
};
