/**
 * generated by JNGU-2012-ExtPlugins. please write here
 * com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList's method:
 * Javascript class static method be used as ExtJs's event method handler,like
 * 'com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.method(); this
 * is Class static method' Javasctipt object method be used as get or set
 * object's properties,like
 * 'com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.prototype.method();
 * this is object's method'
 * com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.PANEL is
 * com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList's Singleton
 * instance object . you can get
 * com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.PANEL's reference
 * by
 * appfram.getInstance('com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList').
 */

/**
 * 存储机构数选择的机构ID
 */
var QryInvestorChannelListInsttuId = '';
var QryInvestorChannelListStart = 0;
/**
 * 页面初始化函数
 */
appframe.afterInstance(
		'com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList',
		function(panel) {
			if (panel) {

				var grid = Ext.getCmp('grid.QryInvestorChannelList');

				grid.getBottomToolbar().doLoad = function(start) {
					QryInvestorChannelListStart = start;
					this.store.load({
								params : {
									'start' : start,
									'limit' : 10
								}
							});
				};
				// 渲染状态下拉框
				Ext.apply(Ext.getCmp('status.QryInvestorChannelList'), {
							store : withholdStateStore.getStore()
						});
				// 渲染业务类型下拉框
				Ext.apply(Ext.getCmp('businessType.QryInvestorChannelList'), {
							store : businessTypeStore2.getStore()
						});
				addWin = appframe
						.getInstance("com.jsjn.jnf.withhold.investor.add.AddInvestorChannelList");
			}
		});
/**
 * 【查询】按钮响应函数
 */
com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.query = function(
		button, event) {
	var status = Ext.getCmp("status.QryInvestorChannelList").getValue();// 状态
	var businessType = Ext.getCmp("businessType.QryInvestorChannelList")
			.getValue();// 渠道
	var channel = Ext.getCmp("channel.QryInvestorChannelList").getValue();// 渠道
	var cardNo = Ext.getCmp("cardNo.QryInvestorChannelList").getValue();// 提现卡号
	var store = Ext.getCmp("grid.QryInvestorChannelList").getStore();// store
	store.baseParams.custId = QryInvestorChannelListInsttuId;
	store.baseParams.state = status;
	store.baseParams.channelId = channel;
	store.baseParams.cardNo = cardNo;
	store.baseParams.businessType = businessType;
	store.load();
};

/**
 * 【新增】按钮响应函数
 */
com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.add = function(
		button, event) {
	Ext.getCmp("insttuNm.AddInvestorChannelList").reset();
	Ext.getCmp("channel.AddInvestorChannelList").reset();
	Ext.getCmp("bindAccNo.AddInvestorChannelList").reset();
	Ext.getCmp("key.AddInvestorChannelList").reset();
	Ext.getCmp("cardNo.AddInvestorChannelList").reset();
	Ext.getCmp("paymentCardNo.AddInvestorChannelList").reset();
	Ext.getCmp("paymentCardName.AddInvestorChannelList").reset();
	// 初始化方法
	addWin.show();
};

/**
 * 【重置】按钮响应函数
 */
com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.rest = function(
		button, event) {
	QryInvestorChannelListInsttuId = '';
	Ext.getCmp("form.QryInvestorChannelList").getForm().reset();//
	var store = Ext.getCmp('channel.QryInvestorChannelList').store;
	Ext.getCmp('channel.QryInvestorChannelList').clearValue();
	store.baseParams = {
		'businessType' : '1'
	};
	store.load();
};

/**
 * 下拉grid选择单行的响应函数
 * 
 * @param {}
 *            combo
 * @param {}
 *            newValue
 * @param {}
 *            oldValue
 */
com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.selectRow = function(
		combo, newValue, oldValue) {
	QryInvestorChannelListInsttuId = newValue;
};

/**
 * 列表数据渲染函数
 * 
 * @param {}
 *            value
 * @param {}
 *            cellmeta
 * @param {}
 *            record
 * @param {}
 *            rowIndex
 * @param {}
 *            columnIndex
 * @param {}
 *            store
 */
com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.rowRenderer = function(
		value, cellmeta, record, rowIndex, columnIndex, store) {
	var grid = Ext.getCmp("grid.QryInvestorChannelList");
	var dataIndex = grid.getColumnModel().getDataIndex(columnIndex);
	if (dataIndex == 'xh') {
		return QryInvestorChannelListStart + 1 + rowIndex;
	} else if (dataIndex == 'operator') {

		if (record.data.state == '2') {

			return "<a href=\"#\" onclick=\"com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.updateStatus(1);\" style=\"vertical-align:bottom; text-decoration:none\">启用</a>";
		} else {

			return "<a href=\"#\" onclick=\"com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.updateStatus(2);\" style=\"vertical-align:bottom; text-decoration:none\">停用</a>";
		}

	} else if (dataIndex == 'state') {

		return storeFind(withholdStateStore, value);
	} else if (dataIndex == 'businessType') {
		return storeFind(businessTypeStore2, value);
	} else if (dataIndex == 'created') {
		return Ext.util.Format.date(value, 'Y-m-d H:i:s');
	}
	return value;
};

/**
 * 停用 OR启用按钮响应函数
 * 
 * @param {}
 *            state
 */
com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.updateStatus = function(
		state) {
	var record = Ext.getCmp('grid.QryInvestorChannelList').getSelectionModel()
			.getSelected();
	Ext.Ajax.request({
				params : {
					id : record.data.id,
					custId : record.data.custId,
					channelId : record.data.channelId,
					state : state
				},
				method : "POST",
				url : appConfig.baseUrl
						+ '/WithholdController.do?method=updateWithholdStatus',
				waitMsg : '正在处理数据...',
				waitTitle : '提示',
				success : function(response) {
					var result = Ext.decode(response.responseText);

					if (result.success) {

						Ext.MessageBox.alert('提示', '操作成功！');
						// 刷新列表
						Ext.getCmp("grid.QryInvestorChannelList").getStore()
								.reload();
					} else {

						Ext.MessageBox.alert('提示', '操作失败！' + result.errMsg);
					}
				}
			});
};

com.jsjn.jnf.withhold.investor.query.QryInvestorChannelList.changeBusinessType = function(
		combo, record, index) {
	var channel = Ext.getCmp('channel.QryInvestorChannelList');
	var businessType = record.get('paramKey');
	if (!valueIsEmpty(businessType)) {
		channel.setReadOnly(false);
		channel.setDisabled(false);
	} else {
		channel.setReadOnly(true);
		channel.setDisabled(true);
	}
	var store = Ext.getCmp('channel.QryInvestorChannelList').store;
	Ext.getCmp('channel.QryInvestorChannelList').clearValue();
	store.baseParams = {
		'businessType' : businessType
	};
	store.load();
}